import json

def add_remaining_vocabulary():
    """Add remaining vocabulary to reach 2000+ words"""

    # Load current vocabulary
    with open("app/src/main/assets/vocabulary_database.json", "r", encoding="utf-8") as f:
        current_vocab = json.load(f)

    existing_words = {item["word"] for item in current_vocab}
    print(f"Current vocabulary: {len(current_vocab)} words")

    # Need approximately 800 more words to reach 2000+
    additional_words = []

    # More Business and Economics vocabulary (200 words)
    business_terms = [
        ("administration", "management of business operations", ["business administration", "public administration"], ["management", "governance", "supervision"], 3, 12),
        ("advertisement", "public notice promoting product", ["television advertisement", "advertisement campaign"], ["promotion", "publicity", "marketing"], 2, 10),
        ("affiliate", "officially attach to organization", ["affiliate company", "affiliate marketing"], ["associate", "partner", "subsidiary"], 3, 13),
        ("agenda", "list of items for meeting", ["meeting agenda", "political agenda"], ["schedule", "program", "plan"], 2, 11),
        ("alliance", "union between organizations", ["strategic alliance", "business alliance"], ["partnership", "coalition", "union"], 3, 12),
        ("analyst", "person who analyzes data", ["financial analyst", "business analyst"], ["examiner", "researcher", "evaluator"], 3, 12),
        ("annual", "occurring once per year", ["annual report", "annual meeting"], ["yearly", "per annum", "once yearly"], 2, 9),
        ("application", "formal request for something", ["job application", "application form"], ["request", "submission", "proposal"], 2, 9),
        ("approach", "way of dealing with situation", ["business approach", "systematic approach"], ["method", "strategy", "technique"], 2, 9),
        ("arrangement", "plan for future event", ["business arrangement", "financial arrangement"], ["agreement", "setup", "organization"], 2, 10),
        ("assembly", "gathering of people", ["assembly line", "general assembly"], ["meeting", "gathering", "collection"], 2, 10),
        ("assessment", "evaluation of nature or quality", ["risk assessment", "performance assessment"], ["evaluation", "appraisal", "analysis"], 3, 11),
        ("assistance", "help given to someone", ["technical assistance", "financial assistance"], ["help", "support", "aid"], 2, 9),
        ("association", "group organized for joint purpose", ["trade association", "professional association"], ["organization", "society", "union"], 2, 10),
        ("assumption", "thing accepted as true", ["business assumption", "basic assumption"], ["presumption", "supposition", "belief"], 3, 11),
        ("assurance", "positive declaration", ["quality assurance", "assurance policy"], ["guarantee", "promise", "confidence"], 3, 12),
        ("attachment", "computer file sent with email", ["email attachment", "document attachment"], ["addition", "appendix", "supplement"], 2, 10),
        ("attendance", "action of being present", ["meeting attendance", "attendance record"], ["presence", "participation", "turnout"], 2, 10),
        ("attraction", "quality of being interesting", ["tourist attraction", "market attraction"], ["appeal", "draw", "magnetism"], 2, 10),
        ("auction", "public sale to highest bidder", ["property auction", "online auction"], ["sale", "bidding", "public sale"], 2, 11),
        ("audit", "official inspection of accounts", ["financial audit", "internal audit"], ["examination", "review", "inspection"], 3, 13),
        ("authorization", "official permission", ["payment authorization", "access authorization"], ["permission", "approval", "clearance"], 3, 13),
        ("availability", "state of being available", ["product availability", "resource availability"], ["accessibility", "presence", "supply"], 2, 10),
        ("backbone", "main support of system", ["backbone infrastructure", "economic backbone"], ["foundation", "core", "support"], 3, 12),
        ("backup", "copy of data for security", ["data backup", "backup system"], ["copy", "reserve", "duplicate"], 2, 10),
        ("balance", "even distribution of weight", ["work-life balance", "balance sheet"], ["equilibrium", "stability", "proportion"], 2, 9),
        ("bandwidth", "range of frequencies", ["internet bandwidth", "bandwidth capacity"], ["capacity", "range", "scope"], 3, 13),
        ("bankruptcy", "legal process for debt relief", ["company bankruptcy", "bankruptcy protection"], ["insolvency", "failure", "collapse"], 4, 16),
        ("baseline", "minimum or starting point", ["baseline measurement", "performance baseline"], ["standard", "benchmark", "reference"], 3, 13),
        ("benchmark", "standard for comparison", ["industry benchmark", "performance benchmark"], ["standard", "reference", "measure"], 3, 13),
        ("blueprint", "detailed plan or design", ["business blueprint", "project blueprint"], ["plan", "design", "scheme"], 3, 12),
        ("boardroom", "room for board meetings", ["boardroom meeting", "boardroom decision"], ["meeting room", "conference room", "executive room"], 3, 13),
        ("bookkeeping", "keeping records of transactions", ["business bookkeeping", "accurate bookkeeping"], ["accounting", "record keeping", "financial records"], 3, 12),
        ("bottleneck", "point of congestion", ["production bottleneck", "traffic bottleneck"], ["obstacle", "constraint", "limitation"], 3, 13),
        ("branding", "marketing practice of creating name", ["corporate branding", "branding strategy"], ["marketing", "identity", "image"], 3, 12),
        ("breakthrough", "sudden important development", ["technological breakthrough", "business breakthrough"], ["advance", "discovery", "progress"], 3, 12),
        ("briefing", "meeting for giving information", ["press briefing", "staff briefing"], ["meeting", "presentation", "update"], 3, 12),
        ("broadcast", "transmit program on radio", ["television broadcast", "news broadcast"], ["transmission", "program", "show"], 2, 10),
        ("brochure", "informational booklet", ["product brochure", "travel brochure"], ["pamphlet", "leaflet", "booklet"], 2, 10),
        ("budget", "estimate of income and expenditure", ["annual budget", "project budget"], ["plan", "allocation", "financial plan"], 2, 9),
        ("bulletin", "short official statement", ["news bulletin", "company bulletin"], ["announcement", "notice", "update"], 2, 10),
        ("bundle", "collection of things bound together", ["software bundle", "product bundle"], ["package", "group", "collection"], 2, 10),
        ("bureau", "office or department", ["employment bureau", "credit bureau"], ["office", "agency", "department"], 3, 12),
        ("calculation", "mathematical computation", ["cost calculation", "profit calculation"], ["computation", "estimate", "assessment"], 2, 10),
        ("calendar", "chart showing days and months", ["business calendar", "meeting calendar"], ["schedule", "timetable", "planner"], 1, 8),
        ("campaign", "organized course of action", ["advertising campaign", "marketing campaign"], ["drive", "effort", "operation"], 2, 10),
        ("candidate", "person running for office", ["job candidate", "presidential candidate"], ["applicant", "nominee", "contender"], 2, 10),
        ("capability", "power or ability", ["technical capability", "production capability"], ["ability", "capacity", "competence"], 3, 11),
        ("capital", "wealth in form of money", ["venture capital", "working capital"], ["money", "funds", "investment"], 2, 10),
        ("caption", "title or explanation", ["photo caption", "table caption"], ["title", "heading", "description"], 2, 10),
        ("career", "occupation undertaken for life", ["career development", "career path"], ["profession", "occupation", "job"], 1, 8),
        ("catalog", "complete list of items", ["product catalog", "course catalog"], ["list", "directory", "index"], 2, 10),
        ("category", "class or division", ["product category", "job category"], ["type", "class", "group"], 2, 9),
        ("caution", "care taken to avoid danger", ["exercise caution", "caution advised"], ["care", "warning", "prudence"], 2, 10),
        ("ceiling", "upper limit", ["price ceiling", "debt ceiling"], ["limit", "maximum", "cap"], 2, 11),
        ("certificate", "official document", ["qualification certificate", "gift certificate"], ["document", "credential", "diploma"], 2, 10),
        ("chain", "series of connected things", ["supply chain", "retail chain"], ["sequence", "series", "network"], 2, 9),
        ("chamber", "large room for meetings", ["chamber of commerce", "meeting chamber"], ["room", "hall", "assembly"], 3, 12),
        ("channel", "medium of communication", ["distribution channel", "communication channel"], ["medium", "route", "pathway"], 2, 10),
        ("charter", "written grant of rights", ["company charter", "project charter"], ["document", "constitution", "license"], 3, 13),
        ("circulation", "movement through closed system", ["magazine circulation", "air circulation"], ["distribution", "flow", "movement"], 3, 12),
        ("classification", "arrangement in classes", ["job classification", "security classification"], ["categorization", "grouping", "organization"], 3, 12),
        ("clause", "particular provision in document", ["contract clause", "escape clause"], ["provision", "condition", "term"], 3, 13),
        ("clearance", "official authorization", ["security clearance", "customs clearance"], ["permission", "approval", "authorization"], 3, 13),
        ("client", "person using services", ["business client", "legal client"], ["customer", "patron", "consumer"], 2, 9),
        ("clinic", "medical facility", ["health clinic", "dental clinic"], ["facility", "center", "office"], 2, 9),
        ("closure", "act of closing", ["plant closure", "road closure"], ["shutdown", "termination", "end"], 3, 12),
        ("coalition", "temporary alliance", ["business coalition", "political coalition"], ["alliance", "partnership", "union"], 4, 15),
        ("code", "system of signals", ["dress code", "ethical code"], ["system", "standard", "rule"], 2, 9),
        ("coincidence", "remarkable concurrence", ["strange coincidence", "mere coincidence"], ["chance", "accident", "fluke"], 3, 12),
        ("collaboration", "action of working together", ["team collaboration", "international collaboration"], ["cooperation", "partnership", "teamwork"], 3, 12),
        ("colleague", "person worked with", ["office colleague", "research colleague"], ["coworker", "associate", "partner"], 2, 9),
        ("collection", "group of collected items", ["art collection", "data collection"], ["gathering", "assembly", "accumulation"], 2, 9),
        ("collision", "instance of colliding", ["vehicle collision", "market collision"], ["crash", "impact", "conflict"], 3, 12),
        ("column", "vertical structure", ["newspaper column", "spreadsheet column"], ["pillar", "post", "section"], 2, 9),
        ("combination", "joining of separate elements", ["winning combination", "color combination"], ["mixture", "blend", "fusion"], 2, 10),
        ("commission", "instruction to produce something", ["art commission", "sales commission"], ["assignment", "fee", "percentage"], 3, 12),
        ("commitment", "state of being dedicated", ["long-term commitment", "financial commitment"], ["dedication", "obligation", "promise"], 3, 11),
        ("committee", "group appointed for function", ["planning committee", "executive committee"], ["panel", "board", "group"], 2, 10),
        ("commodity", "raw material or product", ["agricultural commodity", "precious commodity"], ["product", "goods", "material"], 3, 12),
        ("communication", "means of connection", ["business communication", "verbal communication"], ["contact", "correspondence", "interaction"], 2, 9),
        ("community", "group living together", ["business community", "local community"], ["neighborhood", "society", "group"], 1, 7),
        ("compact", "closely packed together", ["compact design", "compact agreement"], ["small", "dense", "concentrated"], 3, 11),
        ("company", "commercial business", ["technology company", "insurance company"], ["business", "corporation", "firm"], 1, 7),
        ("comparison", "consideration of similarities", ["price comparison", "performance comparison"], ["contrast", "evaluation", "analysis"], 2, 10),
        ("compensation", "something given as payment", ["employee compensation", "injury compensation"], ["payment", "remuneration", "reimbursement"], 3, 13),
        ("competition", "activity of competing", ["market competition", "fierce competition"], ["rivalry", "contest", "race"], 2, 9),
        ("compilation", "collection of works", ["data compilation", "music compilation"], ["collection", "assembly", "gathering"], 3, 13),
        ("complaint", "statement expressing dissatisfaction", ["customer complaint", "formal complaint"], ["grievance", "protest", "objection"], 2, 10),
        ("completion", "action of finishing", ["project completion", "task completion"], ["finish", "conclusion", "end"], 2, 10),
        ("compliance", "conformity with rules", ["regulatory compliance", "safety compliance"], ["adherence", "conformity", "obedience"], 3, 14),
        ("component", "part of larger whole", ["software component", "key component"], ["part", "element", "piece"], 3, 11),
        ("composition", "nature of ingredients", ["team composition", "chemical composition"], ["makeup", "structure", "constitution"], 3, 12),
        ("compound", "thing composed of elements", ["chemical compound", "compound interest"], ["mixture", "combination", "complex"], 3, 12),
        ("compression", "action of compressing", ["data compression", "file compression"], ["reduction", "condensation", "squeezing"], 4, 15),
        ("compromise", "settlement by mutual concession", ["reach compromise", "acceptable compromise"], ["agreement", "settlement", "concession"], 3, 12),
        ("computation", "action of computing", ["mathematical computation", "complex computation"], ["calculation", "processing", "analysis"], 4, 14),
        ("computer", "electronic device for processing", ["personal computer", "computer system"], ["machine", "device", "processor"], 1, 7),
        ("concentration", "close gathering", ["market concentration", "high concentration"], ["focus", "density", "intensity"], 3, 11),
        ("conception", "forming of idea", ["product conception", "original conception"], ["idea", "concept", "notion"], 4, 15),
        ("conclusion", "end or finish", ["meeting conclusion", "logical conclusion"], ["end", "result", "outcome"], 2, 10),
        ("concrete", "solid and real", ["concrete evidence", "concrete plan"], ["solid", "definite", "specific"], 3, 11),
        ("condition", "state of something", ["working condition", "economic condition"], ["state", "situation", "status"], 1, 8),
        ("conference", "formal meeting", ["business conference", "press conference"], ["meeting", "convention", "gathering"], 2, 10),
        ("confidence", "feeling of self-assurance", ["consumer confidence", "business confidence"], ["trust", "faith", "assurance"], 2, 10),
        ("configuration", "arrangement of elements", ["system configuration", "software configuration"], ["setup", "arrangement", "layout"], 4, 15),
        ("confirmation", "action of confirming", ["booking confirmation", "email confirmation"], ["verification", "validation", "proof"], 3, 12),
        ("conflict", "serious disagreement", ["schedule conflict", "workplace conflict"], ["disagreement", "dispute", "clash"], 2, 10),
        ("confusion", "lack of understanding", ["market confusion", "customer confusion"], ["bewilderment", "uncertainty", "disorder"], 2, 10),
        ("connection", "relationship between things", ["internet connection", "business connection"], ["link", "relationship", "association"], 2, 9),
        ("consensus", "general agreement", ["reach consensus", "consensus opinion"], ["agreement", "accord", "unity"], 4, 15),
        ("consequence", "result of action", ["business consequence", "negative consequence"], ["result", "outcome", "effect"], 2, 10),
        ("conservation", "prevention of wasteful use", ["energy conservation", "resource conservation"], ["preservation", "protection", "saving"], 3, 12),
        ("consideration", "careful thought", ["under consideration", "special consideration"], ["thought", "deliberation", "reflection"], 2, 10),
        ("consistency", "conformity in application", ["brand consistency", "quality consistency"], ["reliability", "uniformity", "steadiness"], 3, 12),
        ("consolidation", "combination into single unit", ["debt consolidation", "market consolidation"], ["merger", "combination", "unification"], 4, 16),
        ("consortium", "association of organizations", ["business consortium", "research consortium"], ["partnership", "alliance", "group"], 4, 17),
        ("consultation", "meeting for discussion", ["business consultation", "medical consultation"], ["discussion", "meeting", "advice"], 3, 13),
        ("consumption", "using up of resource", ["energy consumption", "consumer consumption"], ["use", "utilization", "expenditure"], 3, 12),
        ("container", "object for holding", ["shipping container", "storage container"], ["holder", "vessel", "receptacle"], 2, 9),
        ("content", "things contained", ["website content", "course content"], ["material", "substance", "information"], 2, 9),
        ("contest", "competition to win prize", ["design contest", "popularity contest"], ["competition", "rivalry", "challenge"], 2, 10),
        ("context", "circumstances forming setting", ["business context", "cultural context"], ["setting", "background", "environment"], 2, 10),
        ("continuity", "unbroken sequence", ["business continuity", "service continuity"], ["consistency", "stability", "persistence"], 4, 15),
        ("contract", "written agreement", ["employment contract", "service contract"], ["agreement", "deal", "pact"], 2, 10),
        ("contradiction", "combination of opposing statements", ["logical contradiction", "internal contradiction"], ["inconsistency", "conflict", "paradox"], 4, 16),
        ("contribution", "act of giving", ["financial contribution", "team contribution"], ["donation", "input", "addition"], 2, 10),
        ("control", "power to influence", ["quality control", "cost control"], ["management", "supervision", "command"], 1, 8),
        ("controversy", "prolonged disagreement", ["public controversy", "media controversy"], ["debate", "dispute", "argument"], 3, 13),
        ("convention", "way things usually done", ["business convention", "social convention"], ["custom", "tradition", "practice"], 3, 12),
        ("conversation", "informal talk", ["business conversation", "phone conversation"], ["discussion", "chat", "dialogue"], 1, 8),
        ("conversion", "process of changing", ["currency conversion", "file conversion"], ["change", "transformation", "switch"], 3, 12),
        ("cooperation", "process of working together", ["international cooperation", "team cooperation"], ["collaboration", "partnership", "teamwork"], 2, 10),
        ("coordination", "organization of elements", ["project coordination", "team coordination"], ["organization", "management", "synchronization"], 3, 12),
        ("copyright", "exclusive legal right", ["copyright protection", "copyright law"], ["ownership", "patent", "license"], 3, 13),
        ("corporation", "large business organization", ["multinational corporation", "public corporation"], ["company", "business", "enterprise"], 3, 12),
        ("correlation", "mutual relationship", ["positive correlation", "statistical correlation"], ["relationship", "connection", "association"], 4, 14),
        ("correspondence", "communication by letters", ["business correspondence", "email correspondence"], ["communication", "letters", "contact"], 3, 13),
        ("coverage", "extent to which something is covered", ["insurance coverage", "media coverage"], ["protection", "scope", "range"], 2, 11),
        ("creativity", "use of imagination", ["business creativity", "artistic creativity"], ["innovation", "originality", "imagination"], 2, 11),
        ("credibility", "quality of being trusted", ["business credibility", "source credibility"], ["reliability", "trustworthiness", "reputation"], 3, 13),
        ("crisis", "time of intense difficulty", ["financial crisis", "management crisis"], ["emergency", "disaster", "problem"], 3, 12),
        ("criticism", "expression of disapproval", ["constructive criticism", "harsh criticism"], ["critique", "review", "evaluation"], 3, 12),
        ("culture", "ideas and customs", ["company culture", "business culture"], ["environment", "atmosphere", "tradition"], 1, 8),
        ("currency", "system of money", ["foreign currency", "digital currency"], ["money", "cash", "tender"], 2, 11),
        ("customer", "person who buys goods", ["loyal customer", "potential customer"], ["client", "buyer", "consumer"], 1, 7),
        ("cycle", "series of events repeated", ["business cycle", "production cycle"], ["pattern", "sequence", "rotation"], 2, 10),
        ("database", "structured collection of data", ["customer database", "product database"], ["data collection", "information system", "repository"], 3, 12),
        ("deadline", "latest time for completion", ["project deadline", "submission deadline"], ["due date", "time limit", "cutoff"], 2, 10),
        ("dealer", "person who deals in goods", ["car dealer", "authorized dealer"], ["seller", "vendor", "distributor"], 2, 10),
        ("debate", "formal discussion", ["policy debate", "public debate"], ["discussion", "argument", "dialogue"], 2, 10),
        ("debt", "money owed", ["national debt", "business debt"], ["obligation", "liability", "amount owed"], 2, 9),
        ("decade", "period of ten years", ["past decade", "next decade"], ["ten years", "period", "era"], 2, 9),
        ("decision", "conclusion reached", ["business decision", "important decision"], ["choice", "determination", "resolution"], 1, 8),
        ("declaration", "formal announcement", ["independence declaration", "customs declaration"], ["statement", "announcement", "proclamation"], 3, 13),
        ("decline", "gradual deterioration", ["sales decline", "market decline"], ["decrease", "reduction", "fall"], 2, 10),
        ("decoration", "process of decorating", ["office decoration", "holiday decoration"], ["ornamentation", "embellishment", "adornment"], 2, 10),
        ("deduction", "subtraction of amount", ["tax deduction", "payroll deduction"], ["subtraction", "reduction", "discount"], 3, 12),
        ("definition", "exact meaning", ["job definition", "problem definition"], ["meaning", "explanation", "description"], 2, 10),
        ("degree", "extent or level", ["high degree", "degree of difficulty"], ["level", "extent", "amount"], 2, 9),
        ("delivery", "action of delivering", ["package delivery", "service delivery"], ["transport", "shipment", "distribution"], 2, 9),
        ("demand", "urgent request", ["customer demand", "market demand"], ["request", "requirement", "need"], 2, 9),
        ("demonstration", "action of showing", ["product demonstration", "software demonstration"], ["display", "presentation", "showing"], 3, 12),
        ("department", "division of organization", ["sales department", "human resources department"], ["division", "section", "unit"], 2, 9),
        ("deposit", "sum paid into account", ["bank deposit", "security deposit"], ["payment", "down payment", "advance"], 2, 9),
        ("depression", "severe economic downturn", ["economic depression", "market depression"], ["recession", "downturn", "slump"], 3, 13),
        ("description", "spoken account", ["job description", "product description"], ["account", "explanation", "details"], 2, 9),
        ("design", "plan or drawing", ["website design", "product design"], ["plan", "layout", "blueprint"], 1, 8),
        ("destination", "place to which traveling", ["travel destination", "shipping destination"], ["target", "goal", "endpoint"], 2, 10),
        ("destruction", "action of destroying", ["data destruction", "environmental destruction"], ["demolition", "ruin", "devastation"], 3, 12),
        ("detail", "individual fact", ["important detail", "technical detail"], ["fact", "particular", "specification"], 1, 8),
        ("detection", "process of detecting", ["fraud detection", "error detection"], ["discovery", "identification", "finding"], 3, 12),
        ("determination", "firmness of purpose", ["price determination", "strong determination"], ["resolution", "decision", "persistence"], 3, 12),
        ("development", "process of developing", ["business development", "software development"], ["growth", "progress", "advancement"], 2, 9),
        ("device", "piece of equipment", ["electronic device", "security device"], ["tool", "instrument", "gadget"], 2, 9),
        ("diagnosis", "identification of problem", ["medical diagnosis", "system diagnosis"], ["identification", "analysis", "assessment"], 4, 15),
        ("diagram", "simplified drawing", ["flow diagram", "organizational diagram"], ["chart", "illustration", "drawing"], 3, 11),
        ("dialogue", "conversation between people", ["business dialogue", "open dialogue"], ["conversation", "discussion", "talk"], 3, 12),
        ("difference", "point of dissimilarity", ["price difference", "cultural difference"], ["distinction", "variation", "contrast"], 1, 8),
        ("difficulty", "state of being difficult", ["financial difficulty", "technical difficulty"], ["problem", "challenge", "obstacle"], 2, 9),
        ("dimension", "measurable extent", ["business dimension", "problem dimension"], ["aspect", "size", "scope"], 3, 12),
        ("diploma", "certificate awarded", ["college diploma", "training diploma"], ["certificate", "degree", "qualification"], 2, 10),
        ("direction", "course along which moves", ["company direction", "strategic direction"], ["path", "route", "course"], 1, 8),
        ("director", "person who directs", ["company director", "project director"], ["manager", "leader", "supervisor"], 2, 9),
        ("directory", "book listing names", ["phone directory", "business directory"], ["listing", "catalog", "index"], 2, 10),
        ("disability", "physical or mental condition", ["learning disability", "work disability"], ["impairment", "handicap", "condition"], 2, 11),
        ("disagreement", "lack of consensus", ["policy disagreement", "contract disagreement"], ["dispute", "conflict", "difference"], 2, 10),
        ("disaster", "sudden accident", ["natural disaster", "business disaster"], ["catastrophe", "calamity", "emergency"], 2, 11),
        ("discipline", "branch of knowledge", ["academic discipline", "work discipline"], ["field", "subject", "area"], 2, 10),
        ("discount", "deduction from price", ["bulk discount", "employee discount"], ["reduction", "markdown", "rebate"], 2, 9),
        ("discovery", "act of finding", ["scientific discovery", "data discovery"], ["finding", "detection", "revelation"], 2, 10),
        ("discussion", "action of talking", ["team discussion", "board discussion"], ["conversation", "dialogue", "debate"], 1, 8),
        ("disease", "disorder of body", ["occupational disease", "infectious disease"], ["illness", "sickness", "condition"], 2, 9),
        ("display", "performance or show", ["product display", "data display"], ["exhibition", "presentation", "show"], 2, 9),
        ("disposal", "action of getting rid", ["waste disposal", "asset disposal"], ["removal", "elimination", "discarding"], 3, 12),
        ("distribution", "action of sharing out", ["product distribution", "wealth distribution"], ["delivery", "allocation", "spread"], 3, 11),
        ("district", "area of country", ["business district", "school district"], ["area", "region", "zone"], 2, 10),
        ("diversity", "state of being diverse", ["cultural diversity", "product diversity"], ["variety", "range", "mixture"], 3, 12),
        ("division", "action of separating", ["company division", "market division"], ["separation", "section", "department"], 2, 10),
        ("document", "written account", ["legal document", "business document"], ["paper", "record", "file"], 2, 9),
        ("domain", "area of territory", ["business domain", "internet domain"], ["field", "area", "sphere"], 3, 13),
        ("donation", "act of giving", ["charity donation", "blood donation"], ["gift", "contribution", "offering"], 2, 10),
        ("draft", "preliminary version", ["contract draft", "report draft"], ["outline", "sketch", "version"], 2, 11),
        ("drama", "exciting or emotional events", ["workplace drama", "business drama"], ["conflict", "tension", "excitement"], 2, 10),
        ("duration", "time period", ["contract duration", "project duration"], ["length", "period", "span"], 3, 11),
        ("duty", "moral obligation", ["civic duty", "work duty"], ["responsibility", "obligation", "task"], 2, 9),
        ("economy", "wealth of country", ["global economy", "market economy"], ["financial system", "commerce", "trade"], 2, 9),
        ("education", "process of learning", ["business education", "higher education"], ["learning", "training", "schooling"], 1, 7),
        ("effect", "result or consequence", ["side effect", "economic effect"], ["result", "outcome", "impact"], 1, 8),
        ("efficiency", "working without waste", ["energy efficiency", "cost efficiency"], ["effectiveness", "productivity", "performance"], 3, 11),
        ("effort", "vigorous attempt", ["team effort", "marketing effort"], ["attempt", "try", "endeavor"], 1, 8),
        ("election", "formal choice by voting", ["board election", "company election"], ["vote", "selection", "choice"], 2, 10),
        ("element", "essential part", ["key element", "design element"], ["component", "part", "factor"], 2, 9),
        ("emergency", "serious unexpected situation", ["medical emergency", "business emergency"], ["crisis", "urgent situation", "disaster"], 2, 10),
        ("emotion", "strong feeling", ["consumer emotion", "workplace emotion"], ["feeling", "sentiment", "mood"], 2, 9),
        ("emphasis", "special importance", ["business emphasis", "strategic emphasis"], ["stress", "focus", "attention"], 3, 12),
        ("employee", "person employed", ["skilled employee", "full-time employee"], ["worker", "staff member", "personnel"], 1, 7),
        ("employment", "condition of having job", ["full employment", "employment contract"], ["work", "job", "occupation"], 2, 9),
        ("encounter", "unexpected meeting", ["business encounter", "customer encounter"], ["meeting", "experience", "interaction"], 3, 11),
        ("encouragement", "action of encouraging", ["team encouragement", "business encouragement"], ["support", "motivation", "inspiration"], 2, 10),
        ("energy", "power from resources", ["renewable energy", "business energy"], ["power", "force", "strength"], 1, 8),
        ("engagement", "arrangement to meet", ["customer engagement", "employee engagement"], ["involvement", "participation", "commitment"], 3, 12),
        ("engineering", "application of science", ["software engineering", "industrial engineering"], ["design", "construction", "technology"], 3, 12),
        ("enhancement", "action of enhancing", ["product enhancement", "performance enhancement"], ["improvement", "upgrade", "advancement"], 3, 13),
        ("enterprise", "business organization", ["small enterprise", "social enterprise"], ["business", "company", "venture"], 3, 12),
        ("entertainment", "action of entertaining", ["business entertainment", "customer entertainment"], ["amusement", "recreation", "fun"], 2, 10),
        ("enthusiasm", "intense enjoyment", ["team enthusiasm", "business enthusiasm"], ["excitement", "passion", "eagerness"], 3, 12),
        ("environment", "surroundings", ["work environment", "business environment"], ["setting", "surroundings", "atmosphere"], 1, 8),
        ("equipment", "necessary items", ["office equipment", "safety equipment"], ["tools", "apparatus", "gear"], 2, 9),
        ("error", "mistake", ["system error", "calculation error"], ["mistake", "fault", "blunder"], 1, 8),
        ("establishment", "business organization", ["retail establishment", "educational establishment"], ["organization", "institution", "business"], 3, 12),
        ("estimate", "approximate calculation", ["cost estimate", "time estimate"], ["calculation", "assessment", "approximation"], 2, 10),
        ("evaluation", "making judgment", ["performance evaluation", "risk evaluation"], ["assessment", "appraisal", "review"], 3, 11),
        ("event", "thing that happens", ["business event", "special event"], ["occurrence", "happening", "incident"], 1, 8),
        ("evidence", "information indicating", ["market evidence", "business evidence"], ["proof", "indication", "data"], 2, 10),
        ("examination", "detailed inspection", ["financial examination", "market examination"], ["inspection", "review", "analysis"], 3, 11),
        ("example", "thing illustrating principle", ["business example", "practical example"], ["instance", "case", "illustration"], 1, 7),
        ("exception", "person or thing excluded", ["business exception", "rare exception"], ["exclusion", "anomaly", "special case"], 2, 10),
        ("exchange", "act of giving and receiving", ["currency exchange", "information exchange"], ["trade", "swap", "transaction"], 2, 9),
        ("excitement", "feeling of enthusiasm", ["market excitement", "business excitement"], ["enthusiasm", "thrill", "anticipation"], 2, 10),
        ("execution", "carrying out of plan", ["project execution", "strategy execution"], ["implementation", "performance", "completion"], 3, 13),
        ("exercise", "activity for health", ["team exercise", "strategic exercise"], ["activity", "practice", "drill"], 2, 9),
        ("exhibition", "public display", ["trade exhibition", "art exhibition"], ["display", "show", "expo"], 3, 12),
        ("existence", "fact of existing", ["business existence", "market existence"], ["being", "presence", "reality"], 3, 12),
        ("expansion", "action of expanding", ["business expansion", "market expansion"], ["growth", "enlargement", "development"], 3, 11),
        ("expectation", "belief about future", ["customer expectation", "market expectation"], ["anticipation", "hope", "prediction"], 2, 10),
        ("expedition", "journey for purpose", ["business expedition", "research expedition"], ["journey", "trip", "mission"], 3, 13),
        ("expense", "cost incurred", ["business expense", "travel expense"], ["cost", "expenditure", "outlay"], 2, 9),
        ("experience", "practical contact", ["work experience", "customer experience"], ["knowledge", "background", "exposure"], 1, 8),
        ("experiment", "scientific procedure", ["market experiment", "business experiment"], ["test", "trial", "study"], 2, 10),
        ("expert", "person with knowledge", ["business expert", "technical expert"], ["specialist", "authority", "professional"], 2, 9),
        ("explanation", "statement making clear", ["technical explanation", "detailed explanation"], ["clarification", "description", "account"], 2, 9),
        ("exploration", "action of exploring", ["market exploration", "business exploration"], ["investigation", "examination", "research"], 3, 12),
        ("explosion", "violent expansion", ["market explosion", "data explosion"], ["burst", "eruption", "blast"], 3, 12),
        ("export", "sell goods abroad", ["product export", "data export"], ["shipment", "sale abroad", "foreign trade"], 3, 11),
        ("exposure", "state of being exposed", ["market exposure", "brand exposure"], ["visibility", "contact", "experience"], 3, 12),
        ("expression", "process of expressing", ["creative expression", "business expression"], ["communication", "statement", "articulation"], 2, 10),
        ("extension", "action of extending", ["deadline extension", "service extension"], ["expansion", "prolongation", "addition"], 3, 11),
        ("facility", "building for activity", ["manufacturing facility", "training facility"], ["building", "center", "installation"], 2, 10),
        ("factor", "circumstance contributing", ["success factor", "risk factor"], ["element", "component", "aspect"], 2, 9),
        ("failure", "lack of success", ["business failure", "system failure"], ["defeat", "breakdown", "collapse"], 2, 9),
        ("fashion", "popular style", ["business fashion", "current fashion"], ["style", "trend", "mode"], 2, 10),
        ("feature", "distinctive attribute", ["product feature", "special feature"], ["characteristic", "quality", "aspect"], 2, 9),
        ("feedback", "information about reactions", ["customer feedback", "employee feedback"], ["response", "input", "reaction"], 2, 10),
        ("file", "collection of data", ["computer file", "business file"], ["document", "record", "folder"], 1, 8),
        ("finance", "management of money", ["corporate finance", "public finance"], ["money management", "funding", "economics"], 2, 10),
        ("finding", "information discovered", ["research finding", "audit finding"], ["discovery", "result", "conclusion"], 2, 10),
        ("flexibility", "quality of bending", ["schedule flexibility", "business flexibility"], ["adaptability", "versatility", "adjustability"], 3, 12),
        ("flow", "steady movement", ["cash flow", "work flow"], ["movement", "stream", "current"], 2, 9),
        ("focus", "center of interest", ["business focus", "strategic focus"], ["concentration", "attention", "emphasis"], 2, 9),
        ("format", "way arranged", ["file format", "meeting format"], ["layout", "structure", "arrangement"], 2, 10),
        ("foundation", "underlying basis", ["business foundation", "solid foundation"], ["base", "basis", "groundwork"], 2, 10),
        ("framework", "basic structure", ["business framework", "legal framework"], ["structure", "system", "outline"], 3, 12),
        ("frequency", "rate of occurrence", ["meeting frequency", "purchase frequency"], ["rate", "regularity", "occurrence"], 3, 12),
        ("function", "activity proper to", ["business function", "key function"], ["purpose", "role", "operation"], 2, 9),
        ("funding", "money for purpose", ["project funding", "business funding"], ["financing", "capital", "investment"], 3, 11),
        ("future", "time yet to come", ["business future", "near future"], ["tomorrow", "prospect", "outlook"], 1, 7),
        ("generation", "all born same time", ["next generation", "current generation"], ["age group", "era", "period"], 2, 10),
        ("goal", "object of ambition", ["business goal", "personal goal"], ["objective", "target", "aim"], 1, 8),
        ("government", "system by which ruled", ["local government", "federal government"], ["administration", "authority", "state"], 2, 9),
        ("growth", "process of increasing", ["business growth", "economic growth"], ["expansion", "development", "increase"], 2, 9),
        ("guidance", "advice or information", ["business guidance", "expert guidance"], ["direction", "advice", "instruction"], 2, 10),
        ("habitat", "natural environment", ["business habitat", "natural habitat"], ["environment", "home", "territory"], 3, 12),
        ("hardware", "computer equipment", ["computer hardware", "network hardware"], ["equipment", "machinery", "devices"], 3, 11),
        ("health", "state of being well", ["business health", "financial health"], ["wellness", "condition", "fitness"], 1, 8),
        ("heritage", "valued traditions", ["cultural heritage", "business heritage"], ["tradition", "legacy", "inheritance"], 3, 13),
        ("hierarchy", "ranking system", ["business hierarchy", "organizational hierarchy"], ["ranking", "order", "structure"], 4, 15),
        ("history", "study of past", ["company history", "business history"], ["past", "record", "chronicle"], 1, 8),
        ("horizon", "line where earth meets sky", ["business horizon", "time horizon"], ["outlook", "prospect", "future"], 3, 12),
        ("hypothesis", "proposed explanation", ["business hypothesis", "market hypothesis"], ["theory", "assumption", "proposition"], 4, 14),
        ("idea", "thought or suggestion", ["business idea", "innovative idea"], ["concept", "notion", "thought"], 1, 7),
        ("identity", "fact of being", ["brand identity", "corporate identity"], ["character", "nature", "personality"], 2, 10),
        ("image", "representation", ["company image", "brand image"], ["picture", "impression", "reputation"], 1, 8),
        ("impact", "strong effect", ["business impact", "environmental impact"], ["effect", "influence", "consequence"], 2, 10),
        ("implementation", "process of putting into effect", ["strategy implementation", "system implementation"], ["execution", "application", "deployment"], 4, 14),
        ("implication", "possible result", ["business implication", "legal implication"], ["consequence", "result", "meaning"], 3, 13),
        ("import", "bring goods into country", ["product import", "data import"], ["importation", "foreign goods", "bringing in"], 3, 11),
        ("improvement", "example of improving", ["process improvement", "quality improvement"], ["enhancement", "betterment", "upgrade"], 2, 10),
        ("incentive", "thing that motivates", ["employee incentive", "sales incentive"], ["motivation", "encouragement", "reward"], 3, 12),
        ("income", "money received", ["business income", "monthly income"], ["earnings", "revenue", "salary"], 2, 9),
        ("increase", "instance of growing", ["sales increase", "price increase"], ["growth", "rise", "expansion"], 1, 8),
        ("independence", "state of being independent", ["business independence", "financial independence"], ["freedom", "autonomy", "self-reliance"], 3, 12),
        ("index", "alphabetical list", ["price index", "market index"], ["list", "catalog", "directory"], 3, 12),
        ("indication", "sign or piece of information", ["market indication", "business indication"], ["sign", "signal", "evidence"], 3, 11),
        ("industry", "economic activity", ["manufacturing industry", "service industry"], ["business sector", "trade", "commerce"], 2, 9),
        ("inflation", "general increase in prices", ["price inflation", "economic inflation"], ["price rise", "currency devaluation", "cost increase"], 3, 12),
        ("influence", "capacity to effect", ["market influence", "business influence"], ["power", "effect", "impact"], 2, 10),
        ("information", "facts provided", ["business information", "market information"], ["data", "facts", "details"], 1, 8),
        ("infrastructure", "basic facilities", ["business infrastructure", "IT infrastructure"], ["foundation", "framework", "system"], 4, 15),
        ("initiative", "act of taking first step", ["business initiative", "new initiative"], ["action", "step", "measure"], 3, 12),
        ("innovation", "new method or idea", ["business innovation", "technological innovation"], ["invention", "creativity", "novelty"], 3, 11),
        ("input", "what is put in", ["user input", "data input"], ["contribution", "information", "data"], 2, 10),
        ("inspection", "careful examination", ["quality inspection", "safety inspection"], ["examination", "check", "review"], 3, 11),
        ("installation", "action of installing", ["software installation", "equipment installation"], ["setup", "mounting", "placement"], 3, 12),
        ("instance", "example or case", ["business instance", "specific instance"], ["example", "case", "occurrence"], 3, 12),
        ("institution", "established organization", ["financial institution", "educational institution"], ["organization", "establishment", "body"], 3, 12),
        ("instruction", "detailed information", ["user instruction", "work instruction"], ["direction", "guidance", "command"], 2, 9),
        ("instrument", "tool for work", ["financial instrument", "measuring instrument"], ["tool", "device", "equipment"], 3, 11),
        ("insurance", "arrangement for compensation", ["business insurance", "health insurance"], ["protection", "coverage", "policy"], 2, 10),
        ("integration", "action of combining", ["system integration", "business integration"], ["combination", "merger", "unification"], 4, 14),
        ("intelligence", "ability to acquire knowledge", ["business intelligence", "market intelligence"], ["knowledge", "information", "insight"], 2, 10),
        ("intention", "aim or plan", ["business intention", "clear intention"], ["purpose", "goal", "objective"], 3, 11),
        ("interaction", "reciprocal action", ["customer interaction", "business interaction"], ["communication", "contact", "exchange"], 3, 11),
        ("interest", "feeling of curiosity", ["business interest", "customer interest"], ["curiosity", "concern", "attention"], 1, 8),
        ("interface", "point where systems meet", ["user interface", "business interface"], ["connection", "boundary", "link"], 4, 14),
        ("interpretation", "action of explaining", ["data interpretation", "contract interpretation"], ["explanation", "understanding", "analysis"], 3, 13),
        ("interview", "meeting for consultation", ["job interview", "business interview"], ["meeting", "consultation", "discussion"], 2, 10),
        ("introduction", "action of introducing", ["product introduction", "business introduction"], ["presentation", "launch", "debut"], 2, 10),
        ("investment", "action of investing", ["business investment", "capital investment"], ["funding", "capital", "expenditure"], 2, 10),
        ("involvement", "fact of participating", ["employee involvement", "business involvement"], ["participation", "engagement", "inclusion"], 3, 11),
        ("issue", "important topic", ["business issue", "key issue"], ["problem", "matter", "concern"], 2, 9),
        ("item", "individual article", ["business item", "agenda item"], ["object", "thing", "article"], 1, 8),
        ("journal", "newspaper or periodical", ["business journal", "trade journal"], ["publication", "magazine", "periodical"], 2, 10),
        ("judgment", "ability to make decisions", ["business judgment", "professional judgment"], ["decision", "opinion", "assessment"], 3, 11),
        ("justice", "fair treatment", ["business justice", "social justice"], ["fairness", "equity", "righteousness"], 3, 12),
        ("knowledge", "facts and information", ["business knowledge", "expert knowledge"], ["information", "understanding", "expertise"], 1, 8),
        ("laboratory", "room for scientific work", ["research laboratory", "testing laboratory"], ["lab", "facility", "workspace"], 3, 11),
        ("landscape", "visible features of area", ["business landscape", "market landscape"], ["environment", "scene", "setting"], 3, 12),
        ("language", "method of communication", ["business language", "technical language"], ["communication", "speech", "terminology"], 1, 8),
        ("launch", "start or set in motion", ["product launch", "business launch"], ["start", "beginning", "debut"], 2, 10),
        ("law", "system of rules", ["business law", "contract law"], ["regulation", "rule", "statute"], 2, 9),
        ("leader", "person who leads", ["business leader", "team leader"], ["manager", "director", "chief"], 1, 8),
        ("leadership", "action of leading", ["business leadership", "strong leadership"], ["management", "guidance", "direction"], 2, 10),
        ("league", "collection of people", ["business league", "professional league"], ["association", "alliance", "group"], 3, 12),
        ("lecture", "educational talk", ["business lecture", "guest lecture"], ["talk", "presentation", "speech"], 2, 10),
        ("level", "position on scale", ["business level", "performance level"], ["standard", "grade", "degree"], 1, 8),
        ("liability", "state of being liable", ["business liability", "legal liability"], ["responsibility", "obligation", "debt"], 4, 15),
        ("library", "collection of books", ["business library", "digital library"], ["collection", "repository", "archive"], 2, 9),
        ("license", "permit from authority", ["business license", "software license"], ["permit", "authorization", "certificate"], 3, 11),
        ("limitation", "limiting condition", ["business limitation", "time limitation"], ["restriction", "constraint", "boundary"], 3, 12),
        ("link", "relationship between things", ["business link", "strategic link"], ["connection", "relationship", "tie"], 2, 9),
        ("list", "series of items", ["business list", "contact list"], ["catalog", "inventory", "register"], 1, 7),
        ("literature", "written works", ["business literature", "technical literature"], ["writing", "publications", "texts"], 3, 11),
        ("loan", "thing lent", ["business loan", "bank loan"], ["advance", "credit", "lending"], 2, 10),
        ("location", "particular place", ["business location", "office location"], ["place", "position", "site"], 1, 8),
        ("logic", "reasoning according to principles", ["business logic", "sound logic"], ["reasoning", "rationale", "sense"], 3, 11),
        ("loss", "fact of losing", ["business loss", "financial loss"], ["defeat", "failure", "damage"], 2, 9),
        ("loyalty", "strong feeling of support", ["customer loyalty", "brand loyalty"], ["faithfulness", "devotion", "allegiance"], 3, 11),
        ("machine", "apparatus using power", ["business machine", "office machine"], ["device", "equipment", "apparatus"], 1, 8),
        ("magazine", "periodical publication", ["business magazine", "trade magazine"], ["publication", "journal", "periodical"], 2, 9),
        ("maintenance", "process of maintaining", ["equipment maintenance", "system maintenance"], ["upkeep", "care", "preservation"], 3, 11),
        ("management", "process of dealing with", ["business management", "project management"], ["administration", "control", "supervision"], 2, 9),
        ("manual", "handbook", ["user manual", "training manual"], ["handbook", "guide", "instructions"], 2, 10),
        ("manufacture", "make on large scale", ["product manufacture", "goods manufacture"], ["production", "making", "fabrication"], 3, 11),
        ("map", "diagram of area", ["business map", "strategy map"], ["chart", "diagram", "plan"], 1, 8),
        ("margin", "edge or border", ["profit margin", "safety margin"], ["edge", "border", "difference"], 3, 11),
        ("market", "area for commercial dealing", ["business market", "target market"], ["marketplace", "trade", "commerce"], 1, 8),
        ("material", "matter for making", ["business material", "raw material"], ["substance", "matter", "stuff"], 1, 8),
        ("matrix", "rectangular array", ["business matrix", "decision matrix"], ["grid", "table", "framework"], 4, 15),
        ("maximum", "greatest amount possible", ["maximum capacity", "maximum profit"], ["highest", "peak", "top"], 2, 10),
        ("meaning", "what is meant", ["business meaning", "true meaning"], ["significance", "sense", "import"], 1, 8),
        ("measure", "ascertain size", ["performance measure", "safety measure"], ["assessment", "evaluation", "standard"], 2, 9),
        ("mechanism", "system of parts", ["business mechanism", "feedback mechanism"], ["system", "process", "method"], 4, 14),
        ("media", "main means of communication", ["business media", "social media"], ["communication", "press", "channels"], 2, 10),
        ("meeting", "assembly of people", ["business meeting", "team meeting"], ["conference", "gathering", "session"], 1, 7),
        ("member", "person belonging to group", ["team member", "board member"], ["participant", "associate", "colleague"], 1, 8),
        ("memory", "faculty of remembering", ["computer memory", "organizational memory"], ["storage", "recollection", "recall"], 2, 9),
        ("mention", "refer to briefly", ["business mention", "brief mention"], ["reference", "citation", "note"], 2, 10),
        ("message", "verbal communication", ["business message", "email message"], ["communication", "note", "information"], 1, 8),
        ("method", "particular procedure", ["business method", "research method"], ["approach", "technique", "way"], 2, 9),
        ("minimum", "least or smallest amount", ["minimum wage", "minimum requirement"], ["lowest", "smallest", "least"], 2, 10),
        ("mission", "important assignment", ["business mission", "company mission"], ["purpose", "goal", "objective"], 2, 10),
        ("mistake", "action that is wrong", ["business mistake", "common mistake"], ["error", "fault", "blunder"], 1, 8),
        ("model", "representation of something", ["business model", "financial model"], ["example", "pattern", "template"], 2, 9),
        ("modification", "action of modifying", ["product modification", "system modification"], ["change", "alteration", "adjustment"], 4, 14),
        ("module", "standardized part", ["training module", "software module"], ["unit", "component", "section"], 3, 12),
        ("money", "medium of exchange", ["business money", "earned money"], ["currency", "cash", "funds"], 1, 7),
        ("monitor", "observe and check", ["business monitor", "performance monitor"], ["watch", "observe", "track"], 3, 11),
        ("mortgage", "legal agreement for loan", ["business mortgage", "property mortgage"], ["loan", "debt", "financing"], 3, 13),
        ("motion", "action of moving", ["business motion", "forward motion"], ["movement", "action", "activity"], 2, 10),
        ("motivation", "reason for doing", ["employee motivation", "business motivation"], ["incentive", "drive", "inspiration"], 3, 11),
        ("movement", "act of moving", ["business movement", "market movement"], ["motion", "shift", "change"], 2, 9),
        ("muscle", "tissue that contracts", ["business muscle", "financial muscle"], ["strength", "power", "force"], 2, 10),
        ("nature", "inherent characteristics", ["business nature", "human nature"], ["character", "essence", "quality"], 1, 8),
        ("navigation", "process of navigating", ["website navigation", "business navigation"], ["direction", "guidance", "routing"], 3, 12),
        ("necessity", "state of being necessary", ["business necessity", "absolute necessity"], ["requirement", "need", "essential"], 3, 12),
        ("negotiation", "discussion to reach agreement", ["business negotiation", "contract negotiation"], ["discussion", "bargaining", "talks"], 3, 13),
        ("network", "group of connections", ["business network", "computer network"], ["system", "web", "connections"], 2, 10),
        ("news", "newly received information", ["business news", "company news"], ["information", "updates", "reports"], 1, 8),
        ("nomination", "action of nominating", ["board nomination", "award nomination"], ["appointment", "selection", "proposal"], 4, 15),
        ("norm", "standard or pattern", ["business norm", "industry norm"], ["standard", "rule", "convention"], 3, 12),
        ("notice", "attention or observation", ["business notice", "advance notice"], ["warning", "announcement", "alert"], 2, 9),
        ("notification", "action of notifying", ["email notification", "system notification"], ["alert", "notice", "message"], 3, 12),
        ("objective", "goal or aim", ["business objective", "strategic objective"], ["goal", "target", "purpose"], 2, 10),
        ("obligation", "act of being obligated", ["business obligation", "legal obligation"], ["duty", "responsibility", "commitment"], 3, 13),
        ("observation", "action of observing", ["market observation", "business observation"], ["watching", "monitoring", "study"], 3, 11),
        ("obstacle", "thing that blocks", ["business obstacle", "major obstacle"], ["barrier", "hurdle", "impediment"], 3, 12),
        ("occasion", "particular event", ["business occasion", "special occasion"], ["event", "instance", "opportunity"], 2, 10),
        ("occupation", "job or profession", ["business occupation", "professional occupation"], ["job", "career", "profession"], 2, 10),
        ("occurrence", "instance of something happening", ["business occurrence", "rare occurrence"], ["event", "incident", "happening"], 3, 12),
        ("offer", "present for acceptance", ["business offer", "job offer"], ["proposal", "bid", "proposition"], 1, 8),
        ("office", "room for work", ["business office", "head office"], ["workplace", "headquarters", "bureau"], 1, 7),
        ("operation", "action of functioning", ["business operation", "daily operation"], ["functioning", "activity", "process"], 2, 9),
        ("opinion", "view or judgment", ["business opinion", "expert opinion"], ["view", "belief", "thought"], 1, 8),
        ("opportunity", "set of circumstances", ["business opportunity", "career opportunity"], ["chance", "opening", "prospect"], 2, 10),
        ("option", "thing chosen", ["business option", "best option"], ["choice", "alternative", "selection"], 2, 9),
        ("order", "arrangement of things", ["business order", "purchase order"], ["arrangement", "sequence", "command"], 1, 8),
        ("organization", "organized group", ["business organization", "nonprofit organization"], ["company", "institution", "group"], 2, 9),
        ("orientation", "person's attitude", ["business orientation", "customer orientation"], ["direction", "focus", "approach"], 3, 13),
        ("origin", "beginning or source", ["business origin", "country of origin"], ["source", "start", "beginning"], 3, 11),
        ("outcome", "way thing turns out", ["business outcome", "expected outcome"], ["result", "consequence", "effect"], 2, 10),
        ("output", "amount produced", ["business output", "production output"], ["production", "yield", "result"], 2, 10),
        ("overview", "general review", ["business overview", "project overview"], ["summary", "outline", "survey"], 3, 11),
        ("owner", "person who owns", ["business owner", "property owner"], ["proprietor", "holder", "possessor"], 1, 8),
        ("package", "object wrapped for carrying", ["software package", "benefit package"], ["bundle", "parcel", "set"], 2, 9),
        ("panel", "flat piece forming part", ["expert panel", "control panel"], ["board", "committee", "group"], 2, 10),
        ("paper", "material for writing", ["business paper", "research paper"], ["document", "report", "publication"], 1, 8),
        ("parameter", "numerical characteristic", ["business parameter", "system parameter"], ["factor", "variable", "limit"], 4, 15),
        ("parent", "person's father or mother", ["parent company", "parent organization"], ["source", "origin", "base"], 1, 8),
        ("part", "piece or segment", ["business part", "important part"], ["section", "component", "element"], 1, 7),
        ("participant", "person who participates", ["meeting participant", "program participant"], ["member", "attendee", "contributor"], 3, 11),
        ("partnership", "association of partners", ["business partnership", "strategic partnership"], ["alliance", "collaboration", "cooperation"], 3, 12),
        ("passage", "act of going through", ["business passage", "safe passage"], ["movement", "transition", "journey"], 3, 12),
        ("password", "secret word for access", ["system password", "account password"], ["code", "key", "access code"], 2, 10),
        ("patent", "government license", ["business patent", "patent application"], ["license", "copyright", "exclusive right"], 4, 15),
        ("path", "way or track", ["career path", "business path"], ["route", "course", "direction"], 1, 8),
        ("patience", "ability to wait", ["business patience", "great patience"], ["tolerance", "endurance", "perseverance"], 2, 11),
        ("pattern", "repeated design", ["business pattern", "behavior pattern"], ["design", "model", "template"], 2, 9),
        ("payment", "action of paying", ["business payment", "monthly payment"], ["remuneration", "settlement", "fee"], 1, 8),
        ("penalty", "punishment for breaking law", ["business penalty", "late penalty"], ["fine", "punishment", "sanction"], 3, 12),
        ("pension", "regular payment to retired", ["business pension", "retirement pension"], ["retirement fund", "annuity", "benefit"], 3, 13),
        ("percentage", "rate per hundred", ["business percentage", "high percentage"], ["proportion", "fraction", "share"], 2, 10),
        ("performance", "action of performing", ["business performance", "employee performance"], ["execution", "achievement", "results"], 2, 9),
        ("period", "length of time", ["business period", "trial period"], ["time", "duration", "span"], 1, 8),
        ("permission", "action of officially allowing", ["business permission", "written permission"], ["authorization", "approval", "consent"], 2, 10),
        ("permit", "official document giving permission", ["business permit", "work permit"], ["license", "authorization", "pass"], 3, 11),
        ("person", "individual human being", ["business person", "contact person"], ["individual", "human", "someone"], 1, 7),
        ("personality", "combination of characteristics", ["business personality", "strong personality"], ["character", "nature", "temperament"], 2, 10),
        ("perspective", "particular attitude", ["business perspective", "different perspective"], ["viewpoint", "outlook", "angle"], 3, 12),
        ("phase", "distinct period", ["business phase", "development phase"], ["stage", "period", "step"], 2, 10),
        ("philosophy", "study of fundamental nature", ["business philosophy", "company philosophy"], ["principles", "beliefs", "values"], 3, 13),
        ("photograph", "picture made using camera", ["business photograph", "product photograph"], ["photo", "picture", "image"], 2, 9),
        ("phrase", "small group of words", ["business phrase", "key phrase"], ["expression", "term", "saying"], 2, 10),
        ("picture", "visual representation", ["business picture", "complete picture"], ["image", "illustration", "view"], 1, 8),
        ("piece", "portion of object", ["business piece", "key piece"], ["part", "section", "bit"], 1, 7),
        ("plan", "detailed proposal", ["business plan", "strategic plan"], ["strategy", "scheme", "design"], 1, 7),
        ("platform", "raised level surface", ["business platform", "technology platform"], ["base", "foundation", "system"], 2, 10),
        ("point", "particular spot", ["business point", "key point"], ["location", "position", "aspect"], 1, 7),
        ("policy", "course of action", ["business policy", "company policy"], ["strategy", "rule", "procedure"], 2, 9),
        ("politics", "activities of government", ["business politics", "office politics"], ["government", "policy", "power"], 2, 10),
        ("poll", "process of voting", ["opinion poll", "customer poll"], ["survey", "vote", "ballot"], 3, 11),
        ("population", "inhabitants of area", ["target population", "customer population"], ["people", "inhabitants", "community"], 2, 10),
        ("portfolio", "collection of investments", ["business portfolio", "investment portfolio"], ["collection", "range", "selection"], 3, 13),
        ("position", "place where located", ["business position", "market position"], ["location", "place", "role"], 1, 8),
        ("possibility", "thing that may happen", ["business possibility", "future possibility"], ["chance", "prospect", "potential"], 2, 10),
        ("potential", "having possibility", ["business potential", "growth potential"], ["possibility", "capacity", "prospect"], 2, 10),
        ("practice", "actual application", ["business practice", "best practice"], ["method", "procedure", "custom"], 1, 8),
        ("precision", "quality of being exact", ["business precision", "high precision"], ["accuracy", "exactness", "care"], 4, 14),
        ("prediction", "thing predicted", ["business prediction", "market prediction"], ["forecast", "projection", "expectation"], 3, 12),
        ("preference", "greater liking", ["customer preference", "business preference"], ["choice", "inclination", "favor"], 3, 11),
        ("preparation", "action of making ready", ["business preparation", "careful preparation"], ["planning", "arrangement", "setup"], 2, 10),
        ("presence", "state of being present", ["business presence", "market presence"], ["attendance", "existence", "appearance"], 2, 10),
        ("presentation", "action of presenting", ["business presentation", "sales presentation"], ["display", "demonstration", "show"], 2, 10),
        ("pressure", "continuous force", ["business pressure", "time pressure"], ["stress", "force", "strain"], 2, 9),
        ("prevention", "action of stopping", ["business prevention", "accident prevention"], ["avoidance", "protection", "precaution"], 3, 11),
        ("price", "amount expected for something", ["business price", "market price"], ["cost", "fee", "charge"], 1, 7),
        ("principle", "fundamental truth", ["business principle", "guiding principle"], ["rule", "law", "standard"], 2, 10),
        ("priority", "fact of being important", ["business priority", "top priority"], ["importance", "precedence", "urgency"], 3, 11),
        ("privacy", "state of being private", ["business privacy", "data privacy"], ["confidentiality", "secrecy", "isolation"], 3, 12),
        ("procedure", "established way", ["business procedure", "standard procedure"], ["process", "method", "protocol"], 3, 11),
        ("process", "series of actions", ["business process", "manufacturing process"], ["procedure", "method", "operation"], 1, 8),
        ("product", "article manufactured", ["business product", "new product"], ["item", "goods", "commodity"], 1, 7),
        ("production", "action of making", ["business production", "mass production"], ["manufacturing", "creation", "output"], 2, 9),
        ("profession", "paid occupation", ["business profession", "medical profession"], ["career", "occupation", "job"], 2, 9),
        ("profile", "outline of something", ["business profile", "customer profile"], ["description", "summary", "overview"], 3, 11),
        ("profit", "financial gain", ["business profit", "net profit"], ["gain", "earnings", "income"], 2, 9),
        ("program", "planned series of activities", ["business program", "training program"], ["plan", "schedule", "project"], 1, 8),
        ("progress", "forward movement", ["business progress", "steady progress"], ["advancement", "development", "improvement"], 2, 9),
        ("project", "individual enterprise", ["business project", "new project"], ["venture", "undertaking", "scheme"], 1, 8),
        ("promise", "declaration of intention", ["business promise", "firm promise"], ["commitment", "pledge", "assurance"], 1, 8),
        ("promotion", "activity supporting growth", ["business promotion", "sales promotion"], ["advancement", "marketing", "publicity"], 2, 10),
        ("property", "thing owned", ["business property", "intellectual property"], ["possession", "asset", "estate"], 2, 9),
        ("proposal", "plan put forward", ["business proposal", "project proposal"], ["suggestion", "plan", "offer"], 2, 10),
        ("protection", "action of protecting", ["business protection", "data protection"], ["safety", "security", "defense"], 2, 10),
        ("protocol", "official procedure", ["business protocol", "communication protocol"], ["procedure", "etiquette", "standard"], 4, 15),
        ("provision", "action of providing", ["business provision", "service provision"], ["supply", "preparation", "arrangement"], 3, 12),
        ("publication", "book or journal", ["business publication", "research publication"], ["book", "magazine", "document"], 3, 11),
        ("publicity", "notice from public", ["business publicity", "media publicity"], ["promotion", "advertising", "exposure"], 3, 12),
        ("purpose", "reason for existence", ["business purpose", "main purpose"], ["goal", "aim", "objective"], 1, 8),
        ("qualification", "quality fitting person", ["business qualification", "professional qualification"], ["credential", "skill", "ability"], 3, 11),
        ("quality", "standard of excellence", ["business quality", "high quality"], ["standard", "grade", "excellence"], 1, 8),
        ("quantity", "amount or number", ["business quantity", "large quantity"], ["amount", "volume", "number"], 2, 9),
        ("question", "sentence requesting information", ["business question", "important question"], ["inquiry", "query", "issue"], 1, 7),
        ("quote", "repeat words", ["business quote", "price quote"], ["quotation", "estimate", "citation"], 2, 10),
        ("range", "area of variation", ["business range", "price range"], ["variety", "scope", "extent"], 2, 9),
        ("rate", "measure of speed", ["business rate", "growth rate"], ["speed", "pace", "frequency"], 1, 8),
        ("ratio", "quantitative relation", ["business ratio", "profit ratio"], ["proportion", "relationship", "percentage"], 3, 12),
        ("reaction", "action in response", ["market reaction", "customer reaction"], ["response", "reply", "feedback"], 2, 10),
        ("reality", "world as it actually exists", ["business reality", "harsh reality"], ["truth", "fact", "actuality"], 2, 10),
        ("reason", "cause or explanation", ["business reason", "main reason"], ["cause", "explanation", "purpose"], 1, 8),
        ("receipt", "action of receiving", ["business receipt", "payment receipt"], ["acknowledgment", "confirmation", "ticket"], 2, 10),
        ("recognition", "identification of something", ["business recognition", "brand recognition"], ["acknowledgment", "appreciation", "awareness"], 3, 11),
        ("recommendation", "suggestion about best course", ["business recommendation", "expert recommendation"], ["suggestion", "advice", "proposal"], 3, 12),
        ("record", "piece of evidence", ["business record", "sales record"], ["document", "file", "account"], 1, 8),
        ("recovery", "return to normal state", ["business recovery", "economic recovery"], ["restoration", "improvement", "comeback"], 3, 11),
        ("recruitment", "action of finding new people", ["business recruitment", "staff recruitment"], ["hiring", "selection", "employment"], 4, 14),
        ("reduction", "action of making smaller", ["cost reduction", "price reduction"], ["decrease", "cut", "lowering"], 2, 10),
        ("reference", "action of mentioning", ["business reference", "character reference"], ["mention", "citation", "recommendation"], 2, 10),
        ("reflection", "serious thought", ["business reflection", "careful reflection"], ["consideration", "thought", "contemplation"], 3, 12),
        ("region", "area of country", ["business region", "geographic region"], ["area", "territory", "zone"], 2, 9),
        ("registration", "action of registering", ["business registration", "conference registration"], ["enrollment", "recording", "entry"], 3, 12),
        ("regulation", "rule or directive", ["business regulation", "government regulation"], ["rule", "law", "standard"], 3, 11),
        ("relationship", "way connected", ["business relationship", "customer relationship"], ["connection", "association", "bond"], 2, 9),
        ("release", "action of setting free", ["product release", "press release"], ["launch", "publication", "announcement"], 2, 10),
        ("reliability", "quality of being reliable", ["business reliability", "system reliability"], ["dependability", "trustworthiness", "consistency"], 4, 13),
        ("repair", "restore to good condition", ["business repair", "equipment repair"], ["fix", "restoration", "maintenance"], 2, 9),
        ("replacement", "action of replacing", ["business replacement", "staff replacement"], ["substitution", "exchange", "successor"], 3, 11),
        ("report", "account given", ["business report", "annual report"], ["account", "statement", "document"], 1, 8),
        ("representation", "action of speaking for", ["business representation", "legal representation"], ["depiction", "portrayal", "delegation"], 4, 14),
        ("reputation", "beliefs about someone", ["business reputation", "good reputation"], ["standing", "image", "name"], 3, 11),
        ("request", "act of asking", ["business request", "special request"], ["ask", "petition", "application"], 1, 8),
        ("requirement", "thing needed", ["business requirement", "legal requirement"], ["need", "necessity", "condition"], 2, 10),
        ("research", "investigation to establish facts", ["business research", "market research"], ["study", "investigation", "analysis"], 2, 8),
        ("reservation", "action of reserving", ["hotel reservation", "table reservation"], ["booking", "appointment", "arrangement"], 2, 10),
        ("resolution", "firm decision", ["business resolution", "conflict resolution"], ["decision", "solution", "determination"], 3, 12),
        ("resource", "stock that can be drawn on", ["business resource", "human resource"], ["asset", "supply", "material"], 2, 9),
        ("response", "reaction to something", ["business response", "customer response"], ["reply", "answer", "reaction"], 2, 9),
        ("responsibility", "state of being responsible", ["business responsibility", "personal responsibility"], ["duty", "obligation", "accountability"], 3, 11),
        ("restriction", "limiting condition", ["business restriction", "travel restriction"], ["limitation", "constraint", "rule"], 3, 11),
        ("result", "consequence of action", ["business result", "test result"], ["outcome", "consequence", "effect"], 1, 8),
        ("retention", "action of retaining", ["customer retention", "staff retention"], ["keeping", "preservation", "maintenance"], 4, 14),
        ("retirement", "action of leaving job", ["business retirement", "early retirement"], ["withdrawal", "pension", "end of career"], 3, 12),
        ("revenue", "income from business", ["business revenue", "annual revenue"], ["income", "earnings", "receipts"], 3, 11),
        ("review", "formal assessment", ["business review", "performance review"], ["evaluation", "assessment", "examination"], 2, 10),
        ("revolution", "dramatic change", ["business revolution", "digital revolution"], ["transformation", "change", "upheaval"], 3, 12),
        ("reward", "thing given for service", ["business reward", "employee reward"], ["prize", "incentive", "recognition"], 2, 10),
        ("risk", "situation of danger", ["business risk", "financial risk"], ["danger", "hazard", "threat"], 2, 9),
        ("role", "function in process", ["business role", "leadership role"], ["function", "part", "position"], 1, 8),
        ("route", "way taken", ["business route", "delivery route"], ["path", "course", "direction"], 2, 9),
        ("routine", "sequence performed regularly", ["business routine", "daily routine"], ["procedure", "habit", "practice"], 2, 10),
        ("rule", "explicit regulation", ["business rule", "company rule"], ["regulation", "law", "principle"], 1, 8),
        ("safety", "condition of being safe", ["business safety", "workplace safety"], ["security", "protection", "welfare"], 1, 8),
        ("salary", "fixed payment", ["business salary", "annual salary"], ["wage", "pay", "income"], 2, 9),
        ("sale", "exchange for money", ["business sale", "retail sale"], ["selling", "transaction", "deal"], 1, 7),
        ("sample", "small part taken as representative", ["business sample", "product sample"], ["specimen", "example", "test"], 2, 10),
        ("satisfaction", "fulfillment of expectations", ["customer satisfaction", "job satisfaction"], ["contentment", "pleasure", "fulfillment"], 3, 11),
        ("scale", "relative size", ["business scale", "large scale"], ["size", "extent", "scope"], 2, 9),
        ("scenario", "written outline", ["business scenario", "worst case scenario"], ["situation", "plan", "outline"], 3, 12),
        ("schedule", "plan for carrying out", ["business schedule", "meeting schedule"], ["timetable", "plan", "agenda"], 2, 9),
        ("scheme", "systematic plan", ["business scheme", "pension scheme"], ["plan", "system", "program"], 3, 11),
        ("scope", "extent of area", ["business scope", "project scope"], ["range", "extent", "reach"], 3, 11),
        ("screen", "flat surface for projecting", ["computer screen", "screening process"], ["display", "monitor", "filter"], 2, 9),
        ("search", "try to find", ["business search", "job search"], ["hunt", "look", "seek"], 1, 8),
        ("season", "each of four divisions", ["business season", "holiday season"], ["period", "time", "phase"], 1, 8),
        ("section", "distinct part", ["business section", "finance section"], ["part", "division", "segment"], 1, 8),
        ("security", "state of being secure", ["business security", "data security"], ["safety", "protection", "defense"], 2, 9),
        ("selection", "action of selecting", ["business selection", "staff selection"], ["choice", "picking", "option"], 2, 10),
        ("sense", "faculty of perception", ["business sense", "common sense"], ["feeling", "perception", "understanding"], 1, 8),
        ("sequence", "particular order", ["business sequence", "logical sequence"], ["order", "series", "progression"], 3, 11),
        ("series", "number of things", ["business series", "training series"], ["sequence", "set", "collection"], 2, 9),
        ("service", "action of helping", ["business service", "customer service"], ["help", "assistance", "support"], 1, 7),
        ("session", "period devoted to activity", ["business session", "training session"], ["meeting", "period", "conference"], 2, 10),
        ("setting", "place or surroundings", ["business setting", "work setting"], ["environment", "location", "context"], 2, 10),
        ("settlement", "resolution of dispute", ["business settlement", "legal settlement"], ["agreement", "resolution", "payment"], 3, 12),
        ("setup", "way organized", ["business setup", "system setup"], ["arrangement", "configuration", "organization"], 3, 11),
        ("share", "portion of something", ["market share", "business share"], ["part", "portion", "stake"], 1, 8),
        ("shift", "change in position", ["business shift", "night shift"], ["change", "move", "period"], 2, 9),
        ("shortage", "state of being short", ["staff shortage", "supply shortage"], ["lack", "deficit", "scarcity"], 3, 11),
        ("sign", "object conveying information", ["business sign", "warning sign"], ["symbol", "indication", "signal"], 1, 8),
        ("signature", "person's name written", ["business signature", "digital signature"], ["autograph", "name", "mark"], 2, 10),
        ("significance", "quality of being important", ["business significance", "statistical significance"], ["importance", "meaning", "value"], 3, 12),
        ("situation", "set of circumstances", ["business situation", "current situation"], ["condition", "state", "position"], 1, 8),
        ("size", "relative extent", ["business size", "market size"], ["extent", "scale", "dimension"], 1, 7),
        ("skill", "ability to do something", ["business skill", "technical skill"], ["ability", "talent", "expertise"], 1, 8),
        ("society", "community of people", ["business society", "modern society"], ["community", "civilization", "culture"], 2, 9),
        ("software", "computer programs", ["business software", "accounting software"], ["program", "application", "system"], 2, 10),
        ("solution", "means of solving", ["business solution", "technical solution"], ["answer", "resolution", "fix"], 1, 8),
        ("source", "place something comes from", ["business source", "information source"], ["origin", "supplier", "provider"], 2, 9),
        ("space", "continuous area", ["business space", "office space"], ["room", "area", "place"], 1, 7),
        ("specialist", "person concentrated on area", ["business specialist", "technical specialist"], ["expert", "professional", "authority"], 3, 11),
        ("specification", "detailed description", ["product specification", "technical specification"], ["requirement", "description", "standard"], 4, 14),
        ("speed", "rate of movement", ["business speed", "processing speed"], ["pace", "velocity", "rate"], 1, 8),
        ("stage", "point in process", ["business stage", "development stage"], ["phase", "step", "period"], 2, 9),
        ("standard", "level of quality", ["business standard", "quality standard"], ["norm", "benchmark", "criterion"], 2, 9),
        ("statement", "definite account", ["business statement", "financial statement"], ["declaration", "report", "account"], 2, 9),
        ("statistics", "numerical data", ["business statistics", "sales statistics"], ["data", "figures", "numbers"], 3, 11),
        ("status", "relative position", ["business status", "employment status"], ["position", "standing", "state"], 2, 10),
        ("step", "act of lifting foot", ["business step", "first step"], ["action", "stage", "move"], 1, 7),
        ("stock", "goods kept on premises", ["business stock", "stock market"], ["inventory", "supply", "shares"], 2, 9),
        ("storage", "action of storing", ["data storage", "business storage"], ["keeping", "warehouse", "repository"], 2, 10),
        ("strategy", "plan of action", ["business strategy", "marketing strategy"], ["plan", "approach", "method"], 2, 10),
        ("structure", "arrangement of parts", ["business structure", "organizational structure"], ["organization", "framework", "system"], 2, 9),
        ("study", "detailed investigation", ["business study", "market study"], ["research", "analysis", "examination"], 1, 8),
        ("style", "manner of doing", ["business style", "management style"], ["approach", "method", "way"], 1, 8),
        ("subject", "person under political rule", ["business subject", "subject matter"], ["topic", "theme", "area"], 1, 8),
        ("success", "accomplishment of aim", ["business success", "great success"], ["achievement", "victory", "triumph"], 1, 8),
        ("suggestion", "idea put forward", ["business suggestion", "helpful suggestion"], ["proposal", "recommendation", "idea"], 2, 10),
        ("summary", "brief statement", ["business summary", "executive summary"], ["overview", "outline", "abstract"], 2, 10),
        ("supply", "stock of resource", ["business supply", "water supply"], ["provision", "stock", "source"], 2, 9),
        ("support", "bear weight of", ["business support", "technical support"], ["help", "assistance", "backing"], 1, 8),
        ("survey", "general view", ["business survey", "customer survey"], ["study", "investigation", "poll"], 2, 10),
        ("survival", "state of continuing to live", ["business survival", "economic survival"], ["continuation", "persistence", "endurance"], 3, 12),
        ("system", "organized whole", ["business system", "computer system"], ["organization", "structure", "method"], 1, 8),
        ("table", "piece of furniture", ["business table", "conference table"], ["desk", "chart", "list"], 1, 7),
        ("target", "person or thing aimed at", ["business target", "sales target"], ["goal", "objective", "aim"], 2, 9),
        ("task", "piece of work", ["business task", "assigned task"], ["job", "duty", "assignment"], 1, 7),
        ("tax", "compulsory contribution", ["business tax", "income tax"], ["levy", "duty", "charge"], 2, 9),
        ("team", "group working together", ["business team", "management team"], ["group", "squad", "crew"], 1, 7),
        ("technique", "way of carrying out", ["business technique", "sales technique"], ["method", "approach", "skill"], 2, 10),
        ("technology", "application of science", ["business technology", "information technology"], ["innovation", "advancement", "system"], 2, 9),
        ("telephone", "system for voice transmission", ["business telephone", "office telephone"], ["phone", "communication device", "handset"], 1, 8),
        ("template", "shaped piece used as guide", ["business template", "document template"], ["pattern", "model", "format"], 3, 12),
        ("territory", "area of land", ["business territory", "sales territory"], ["region", "area", "zone"], 3, 11),
        ("test", "procedure to establish quality", ["business test", "market test"], ["trial", "examination", "check"], 1, 8),
        ("text", "written words", ["business text", "contract text"], ["writing", "content", "document"], 1, 8),
        ("theory", "supposition explaining something", ["business theory", "economic theory"], ["hypothesis", "concept", "idea"], 2, 10),
        ("threat", "statement of intention to harm", ["business threat", "security threat"], ["danger", "risk", "menace"], 3, 11),
        ("time", "indefinite continued progress", ["business time", "working time"], ["period", "duration", "moment"], 1, 6),
        ("title", "name of book or work", ["business title", "job title"], ["name", "heading", "position"], 1, 8),
        ("tool", "device used to carry out", ["business tool", "management tool"], ["instrument", "equipment", "device"], 1, 8),
        ("topic", "subject of conversation", ["business topic", "discussion topic"], ["subject", "theme", "issue"], 2, 9),
        ("total", "comprising whole number", ["business total", "grand total"], ["sum", "whole", "complete"], 1, 8),
        ("track", "rough path", ["business track", "fast track"], ["path", "route", "record"], 1, 8),
        ("trade", "buying and selling", ["business trade", "international trade"], ["commerce", "business", "exchange"], 2, 9),
        ("tradition", "transmission of customs", ["business tradition", "family tradition"], ["custom", "practice", "heritage"], 2, 10),
        ("traffic", "vehicles moving on road", ["business traffic", "website traffic"], ["movement", "flow", "activity"], 2, 9),
        ("training", "action of teaching", ["business training", "staff training"], ["education", "instruction", "development"], 2, 9),
        ("transaction", "instance of buying or selling", ["business transaction", "financial transaction"], ["deal", "exchange", "trade"], 3, 11),
        ("transfer", "move from one place", ["business transfer", "data transfer"], ["move", "shift", "relocation"], 2, 10),
        ("transformation", "marked change", ["business transformation", "digital transformation"], ["change", "conversion", "metamorphosis"], 4, 14),
        ("translation", "process of translating", ["business translation", "document translation"], ["conversion", "interpretation", "rendering"], 3, 12),
        ("transport", "system of carrying", ["business transport", "public transport"], ["transportation", "delivery", "movement"], 2, 9),
        ("travel", "journey from one place", ["business travel", "international travel"], ["journey", "trip", "movement"], 1, 8),
        ("treatment", "manner of behaving toward", ["business treatment", "fair treatment"], ["handling", "behavior", "approach"], 2, 9),
        ("trend", "general direction of change", ["business trend", "market trend"], ["direction", "pattern", "movement"], 2, 10),
        ("trial", "formal examination", ["business trial", "free trial"], ["test", "experiment", "attempt"], 2, 10),
        ("trust", "firm belief in reliability", ["business trust", "customer trust"], ["confidence", "faith", "reliance"], 2, 9),
        ("truth", "quality of being true", ["business truth", "absolute truth"], ["fact", "reality", "honesty"], 2, 9),
        ("type", "category of things", ["business type", "document type"], ["kind", "sort", "category"], 1, 8),
        ("understanding", "ability to understand", ["business understanding", "mutual understanding"], ["comprehension", "knowledge", "agreement"], 2, 9),
        ("union", "action of joining", ["business union", "trade union"], ["alliance", "merger", "association"], 3, 11),
        ("unit", "individual thing regarded as separate", ["business unit", "production unit"], ["section", "division", "component"], 2, 9),
        ("update", "make more modern", ["business update", "software update"], ["upgrade", "revision", "improvement"], 2, 10),
        ("usage", "action of using", ["business usage", "energy usage"], ["use", "utilization", "consumption"], 3, 11),
        ("user", "person who uses", ["business user", "system user"], ["operator", "customer", "consumer"], 2, 9),
        ("utility", "state of being useful", ["business utility", "public utility"], ["usefulness", "service", "benefit"], 3, 12),
        ("vacation", "extended period of leisure", ["business vacation", "summer vacation"], ["holiday", "break", "time off"], 2, 10),
        ("value", "importance or worth", ["business value", "market value"], ["worth", "importance", "benefit"], 1, 8),
        ("variable", "element that may change", ["business variable", "market variable"], ["factor", "element", "component"], 3, 11),
        ("variety", "quality of being different", ["business variety", "wide variety"], ["diversity", "range", "selection"], 2, 10),
        ("vehicle", "thing used for transporting", ["business vehicle", "motor vehicle"], ["transport", "means", "method"], 2, 9),
        ("venture", "risky undertaking", ["business venture", "joint venture"], ["enterprise", "project", "undertaking"], 3, 12),
        ("version", "particular form", ["business version", "latest version"], ["variant", "edition", "form"], 2, 10),
        ("view", "ability to see", ["business view", "different view"], ["opinion", "perspective", "sight"], 1, 8),
        ("vision", "ability to see", ["business vision", "clear vision"], ["sight", "dream", "goal"], 2, 10),
        ("visit", "go to see", ["business visit", "site visit"], ["call", "trip", "meeting"], 1, 8),
        ("volume", "amount of space", ["business volume", "sales volume"], ["amount", "quantity", "size"], 2, 9),
        ("warning", "statement alerting to danger", ["business warning", "advance warning"], ["alert", "caution", "notice"], 2, 10),
        ("waste", "use carelessly", ["business waste", "food waste"], ["squander", "garbage", "loss"], 2, 9),
        ("wealth", "abundance of possessions", ["business wealth", "personal wealth"], ["riches", "prosperity", "fortune"], 3, 11),
        ("website", "location on internet", ["business website", "company website"], ["site", "webpage", "portal"], 2, 10),
        ("welfare", "health and happiness", ["employee welfare", "social welfare"], ["wellbeing", "benefit", "good"], 3, 12),
        ("width", "measurement from side to side", ["business width", "page width"], ["breadth", "span", "extent"], 2, 10),
        ("wisdom", "quality of having experience", ["business wisdom", "conventional wisdom"], ["knowledge", "insight", "understanding"], 3, 12),
        ("witness", "person who sees event", ["business witness", "eye witness"], ["observer", "spectator", "testifier"], 3, 11),
        ("work", "activity involving effort", ["business work", "hard work"], ["labor", "job", "effort"], 1, 6),
        ("workshop", "meeting for discussion", ["business workshop", "training workshop"], ["seminar", "session", "class"], 2, 10),
        ("world", "earth with inhabitants", ["business world", "modern world"], ["globe", "planet", "society"], 1, 7),
        ("worth", "value equivalent to", ["business worth", "net worth"], ["value", "merit", "importance"], 2, 9),
        ("writing", "activity of writing", ["business writing", "technical writing"], ["text", "composition", "script"], 1, 8),
        ("zone", "area distinguished from adjacent parts", ["business zone", "time zone"], ["area", "region", "sector"], 2, 10)
    ]

    # Create entries for business terms
    for word, definition, contexts, related_words, difficulty, week in business_terms:
        if word not in existing_words:
            entry = {
                "word": word,
                "definition": definition,
                "difficulty": difficulty,
                "category": "BUSINESS",
                "contexts": contexts,
                "relatedWords": related_words,
                "grammarPattern": determine_grammar_pattern(word),
                "weekIntroduced": week
            }
            additional_words.append(entry)
            existing_words.add(word)

    # Add remaining additional words to reach 2000+
    return additional_words

def determine_grammar_pattern(word):
    """Determine grammar pattern based on word characteristics"""
    if word.endswith('ing'):
        return "gerund_or_present_participle"
    elif word.endswith(('tion', 'sion')):
        return "noun_from_verb"
    elif word.endswith(('able', 'ible')):
        return "adjective_suffix"
    elif word.endswith('ism'):
        return "abstract_noun"
    elif word.endswith(('ity', 'ty')):
        return "noun_quality"
    elif word.endswith(('ize', 'ise')):
        return "verb_suffix"
    elif word.endswith('ly'):
        return "adverb"
    elif word.endswith(('ous', 'ious')):
        return "adjective_suffix"
    elif word.endswith(('ent', 'ant')):
        return "adjective_or_noun"
    else:
        return None

if __name__ == "__main__":
    additional_vocab = add_remaining_vocabulary()

    # Load current vocabulary and add new words
    with open("app/src/main/assets/vocabulary_database.json", "r", encoding="utf-8") as f:
        current_vocab = json.load(f)

    # Combine and save
    complete_vocab = current_vocab + additional_vocab

    with open("app/src/main/assets/vocabulary_database.json", "w", encoding="utf-8") as f:
        json.dump(complete_vocab, f, indent=2, ensure_ascii=False)

    print(f"Added {len(additional_vocab)} new words")
    print(f"Total vocabulary: {len(complete_vocab)} words")

    # Category distribution
    categories = {}
    for entry in complete_vocab:
        cat = entry.get('category', 'UNKNOWN')
        categories[cat] = categories.get(cat, 0) + 1

    print(f"Final category distribution: {categories}")