#!/usr/bin/env python3
import json
import os

def load_vocabulary():
    try:
        with open('app/src/main/assets/vocabulary_database.json', 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_vocabulary(data):
    os.makedirs('app/src/main/assets', exist_ok=True)
    with open('app/src/main/assets/vocabulary_database.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def add_final_academic_vocabulary():
    return [
        # Science and research (60 words)
        {"word": "anthropology", "definition": "study of humankind", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Cultural anthropology", "Study anthropology"], "relatedWords": ["humanity", "culture", "society"], "grammarPattern": "anthropology + of/in", "weekIntroduced": 25},
        {"word": "archaeology", "definition": "study of human history through excavation", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Archaeological dig", "Study archaeology"], "relatedWords": ["excavation", "history", "artifacts"], "grammarPattern": "archaeology + of/in", "weekIntroduced": 26},
        {"word": "paleontology", "definition": "study of fossil organisms", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study paleontology", "Paleontological evidence"], "relatedWords": ["fossils", "evolution", "geology"], "grammarPattern": "paleontology + of/in", "weekIntroduced": 28},
        {"word": "geology", "definition": "science of earth's physical structure", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study geology", "Geological formation"], "relatedWords": ["earth", "rocks", "minerals"], "grammarPattern": "geology + of/in", "weekIntroduced": 22},
        {"word": "meteorology", "definition": "study of weather and atmospheric conditions", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study meteorology", "Meteorological data"], "relatedWords": ["weather", "atmosphere", "climate"], "grammarPattern": "meteorology + of/in", "weekIntroduced": 25},
        {"word": "astronomy", "definition": "study of celestial objects", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study astronomy", "Astronomical observation"], "relatedWords": ["stars", "planets", "universe"], "grammarPattern": "astronomy + of/in", "weekIntroduced": 21},
        {"word": "astrophysics", "definition": "physics of stellar phenomena", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study astrophysics", "Astrophysical research"], "relatedWords": ["stars", "physics", "universe"], "grammarPattern": "astrophysics + of/in", "weekIntroduced": 27},
        {"word": "cosmology", "definition": "science of origin and development of universe", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study cosmology", "Cosmological theory"], "relatedWords": ["universe", "origin", "space"], "grammarPattern": "cosmology + of/in", "weekIntroduced": 28},
        {"word": "seismology", "definition": "study of earthquakes", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study seismology", "Seismological data"], "relatedWords": ["earthquakes", "geology", "waves"], "grammarPattern": "seismology + of/in", "weekIntroduced": 29},
        {"word": "oceanography", "definition": "study of ocean", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study oceanography", "Oceanographic research"], "relatedWords": ["ocean", "marine", "water"], "grammarPattern": "oceanography + of/in", "weekIntroduced": 26},
        {"word": "hydrology", "definition": "study of water movement", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study hydrology", "Hydrological cycle"], "relatedWords": ["water", "flow", "cycle"], "grammarPattern": "hydrology + of/in", "weekIntroduced": 27},
        {"word": "botany", "definition": "study of plants", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study botany", "Botanical garden"], "relatedWords": ["plants", "vegetation", "flora"], "grammarPattern": "botany + of/in", "weekIntroduced": 22},
        {"word": "zoology", "definition": "study of animals", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study zoology", "Zoological research"], "relatedWords": ["animals", "fauna", "biology"], "grammarPattern": "zoology + of/in", "weekIntroduced": 23},
        {"word": "entomology", "definition": "study of insects", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study entomology", "Entomological research"], "relatedWords": ["insects", "bugs", "biology"], "grammarPattern": "entomology + of/in", "weekIntroduced": 29},
        {"word": "ornithology", "definition": "study of birds", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study ornithology", "Ornithological observation"], "relatedWords": ["birds", "avian", "biology"], "grammarPattern": "ornithology + of/in", "weekIntroduced": 30},
        {"word": "ichthyology", "definition": "study of fish", "difficulty": 9, "category": "ACADEMIC", "contexts": ["Study ichthyology", "Ichthyological research"], "relatedWords": ["fish", "aquatic", "marine"], "grammarPattern": "ichthyology + of/in", "weekIntroduced": 30},
        {"word": "microbiology", "definition": "study of microorganisms", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study microbiology", "Microbiological analysis"], "relatedWords": ["bacteria", "microbes", "organisms"], "grammarPattern": "microbiology + of/in", "weekIntroduced": 25},
        {"word": "virology", "definition": "study of viruses", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study virology", "Virological research"], "relatedWords": ["viruses", "infection", "disease"], "grammarPattern": "virology + of/in", "weekIntroduced": 26},
        {"word": "immunology", "definition": "study of immune system", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study immunology", "Immunological response"], "relatedWords": ["immunity", "defense", "antibodies"], "grammarPattern": "immunology + of/in", "weekIntroduced": 27},
        {"word": "neurology", "definition": "study of nervous system", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study neurology", "Neurological examination"], "relatedWords": ["brain", "nerves", "nervous"], "grammarPattern": "neurology + of/in", "weekIntroduced": 25},
        {"word": "cardiology", "definition": "study of heart and circulatory system", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study cardiology", "Cardiological examination"], "relatedWords": ["heart", "circulation", "cardiovascular"], "grammarPattern": "cardiology + of/in", "weekIntroduced": 26},
        {"word": "dermatology", "definition": "study of skin", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study dermatology", "Dermatological treatment"], "relatedWords": ["skin", "dermal", "medical"], "grammarPattern": "dermatology + of/in", "weekIntroduced": 27},
        {"word": "ophthalmology", "definition": "study of eye and vision", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study ophthalmology", "Ophthalmological examination"], "relatedWords": ["eyes", "vision", "sight"], "grammarPattern": "ophthalmology + of/in", "weekIntroduced": 29},
        {"word": "otolaryngology", "definition": "study of ear, nose, and throat", "difficulty": 9, "category": "ACADEMIC", "contexts": ["Study otolaryngology", "Otolaryngological examination"], "relatedWords": ["ear", "nose", "throat"], "grammarPattern": "otolaryngology + of/in", "weekIntroduced": 30},
        {"word": "gastroenterology", "definition": "study of digestive system", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study gastroenterology", "Gastroenterological procedure"], "relatedWords": ["digestive", "stomach", "intestine"], "grammarPattern": "gastroenterology + of/in", "weekIntroduced": 29},
        {"word": "endocrinology", "definition": "study of endocrine system", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study endocrinology", "Endocrinological disorder"], "relatedWords": ["hormones", "glands", "endocrine"], "grammarPattern": "endocrinology + of/in", "weekIntroduced": 28},
        {"word": "epidemiology", "definition": "study of disease patterns", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study epidemiology", "Epidemiological study"], "relatedWords": ["disease", "patterns", "public health"], "grammarPattern": "epidemiology + of/in", "weekIntroduced": 27},
        {"word": "toxicology", "definition": "study of toxic substances", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study toxicology", "Toxicological analysis"], "relatedWords": ["poison", "toxic", "harmful"], "grammarPattern": "toxicology + of/in", "weekIntroduced": 26},
        {"word": "pharmacokinetics", "definition": "study of drug movement in body", "difficulty": 9, "category": "ACADEMIC", "contexts": ["Study pharmacokinetics", "Pharmacokinetic analysis"], "relatedWords": ["drugs", "absorption", "metabolism"], "grammarPattern": "pharmacokinetics + of/in", "weekIntroduced": 30},
        {"word": "pharmacodynamics", "definition": "study of drug effects on body", "difficulty": 9, "category": "ACADEMIC", "contexts": ["Study pharmacodynamics", "Pharmacodynamic effects"], "relatedWords": ["drugs", "effects", "mechanism"], "grammarPattern": "pharmacodynamics + of/in", "weekIntroduced": 30},
        {"word": "genetics", "definition": "study of heredity and genes", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study genetics", "Genetic analysis"], "relatedWords": ["genes", "heredity", "DNA"], "grammarPattern": "genetics + of/in", "weekIntroduced": 21},
        {"word": "genomics", "definition": "study of complete DNA sequence", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study genomics", "Genomic analysis"], "relatedWords": ["genome", "DNA", "sequence"], "grammarPattern": "genomics + of/in", "weekIntroduced": 25},
        {"word": "proteomics", "definition": "study of proteins", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study proteomics", "Proteomic analysis"], "relatedWords": ["proteins", "structure", "function"], "grammarPattern": "proteomics + of/in", "weekIntroduced": 28},
        {"word": "bioinformatics", "definition": "application of computer science to biology", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study bioinformatics", "Bioinformatics analysis"], "relatedWords": ["computer", "biology", "data"], "grammarPattern": "bioinformatics + in/of", "weekIntroduced": 27},
        {"word": "cybernetics", "definition": "study of communication and control", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study cybernetics", "Cybernetic system"], "relatedWords": ["control", "communication", "feedback"], "grammarPattern": "cybernetics + of/in", "weekIntroduced": 29},
        {"word": "statistics", "definition": "practice of collecting and analyzing data", "difficulty": 5, "category": "ACADEMIC", "contexts": ["Statistical analysis", "Study statistics"], "relatedWords": ["data", "analysis", "numbers"], "grammarPattern": "statistics + of/in", "weekIntroduced": 18},
        {"word": "mathematics", "definition": "abstract science of number and space", "difficulty": 5, "category": "ACADEMIC", "contexts": ["Study mathematics", "Mathematical proof"], "relatedWords": ["numbers", "calculations", "logic"], "grammarPattern": "mathematics + of/in", "weekIntroduced": 17},
        {"word": "calculus", "definition": "mathematics of continuous change", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study calculus", "Calculus problem"], "relatedWords": ["mathematics", "derivatives", "integrals"], "grammarPattern": "calculus + problem/in", "weekIntroduced": 24},
        {"word": "algebra", "definition": "branch of mathematics using letters", "difficulty": 5, "category": "ACADEMIC", "contexts": ["Study algebra", "Algebraic equation"], "relatedWords": ["mathematics", "equations", "variables"], "grammarPattern": "algebra + problem/in", "weekIntroduced": 17},
        {"word": "geometry", "definition": "branch of mathematics concerned with shapes", "difficulty": 5, "category": "ACADEMIC", "contexts": ["Study geometry", "Geometric shape"], "relatedWords": ["shapes", "angles", "space"], "grammarPattern": "geometry + of/in", "weekIntroduced": 16},
        {"word": "trigonometry", "definition": "study of triangles and their angles", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study trigonometry", "Trigonometric function"], "relatedWords": ["triangles", "angles", "functions"], "grammarPattern": "trigonometry + in/of", "weekIntroduced": 21},
        {"word": "topology", "definition": "study of geometric properties", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study topology", "Topological space"], "relatedWords": ["geometry", "space", "properties"], "grammarPattern": "topology + of/in", "weekIntroduced": 27},
        {"word": "linguistics", "definition": "scientific study of language", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study linguistics", "Linguistic analysis"], "relatedWords": ["language", "grammar", "syntax"], "grammarPattern": "linguistics + of/in", "weekIntroduced": 20},
        {"word": "phonetics", "definition": "study of speech sounds", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study phonetics", "Phonetic transcription"], "relatedWords": ["sounds", "pronunciation", "speech"], "grammarPattern": "phonetics + of/in", "weekIntroduced": 24},
        {"word": "semantics", "definition": "study of meaning in language", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study semantics", "Semantic analysis"], "relatedWords": ["meaning", "language", "interpretation"], "grammarPattern": "semantics + of/in", "weekIntroduced": 25},
        {"word": "pragmatics", "definition": "study of language in context", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study pragmatics", "Pragmatic analysis"], "relatedWords": ["context", "usage", "communication"], "grammarPattern": "pragmatics + of/in", "weekIntroduced": 26},
        {"word": "syntax", "definition": "arrangement of words to create sentences", "difficulty": 6, "category": "ACADEMIC", "contexts": ["Study syntax", "Syntactic analysis"], "relatedWords": ["grammar", "structure", "sentences"], "grammarPattern": "syntax + of/in", "weekIntroduced": 22},
        {"word": "phonology", "definition": "study of sounds in language", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study phonology", "Phonological rule"], "relatedWords": ["sounds", "language", "patterns"], "grammarPattern": "phonology + of/in", "weekIntroduced": 25},
        {"word": "morphology", "definition": "study of word structure", "difficulty": 7, "category": "ACADEMIC", "contexts": ["Study morphology", "Morphological analysis"], "relatedWords": ["words", "structure", "formation"], "grammarPattern": "morphology + of/in", "weekIntroduced": 24},
        {"word": "lexicology", "definition": "study of words and vocabulary", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study lexicology", "Lexicological analysis"], "relatedWords": ["words", "vocabulary", "meaning"], "grammarPattern": "lexicology + of/in", "weekIntroduced": 27},
        {"word": "sociolinguistics", "definition": "study of language in social context", "difficulty": 8, "category": "ACADEMIC", "contexts": ["Study sociolinguistics", "Sociolinguistic analysis"], "relatedWords": ["language", "society", "culture"], "grammarPattern": "sociolinguistics + of/in", "weekIntroduced": 28}
    ]

def add_final_business_vocabulary():
    return [
        # Business and finance (60 words)
        {"word": "entrepreneurship", "definition": "activity of setting up business", "difficulty": 7, "category": "BUSINESS", "contexts": ["Study entrepreneurship", "Entrepreneurship program"], "relatedWords": ["business", "startup", "innovation"], "grammarPattern": "entrepreneurship + in/program", "weekIntroduced": 25},
        {"word": "franchising", "definition": "practice of using another's business model", "difficulty": 6, "category": "BUSINESS", "contexts": ["Franchise business", "Franchising opportunity"], "relatedWords": ["business", "license", "expansion"], "grammarPattern": "franchising + opportunity/business", "weekIntroduced": 23},
        {"word": "licensing", "definition": "granting permission to use property", "difficulty": 6, "category": "BUSINESS", "contexts": ["Software licensing", "Brand licensing"], "relatedWords": ["permission", "rights", "agreement"], "grammarPattern": "licensing + agreement/deal", "weekIntroduced": 22},
        {"word": "merchandising", "definition": "promotion of sale of goods", "difficulty": 6, "category": "BUSINESS", "contexts": ["Product merchandising", "Retail merchandising"], "relatedWords": ["promotion", "sales", "display"], "grammarPattern": "merchandising + strategy/plan", "weekIntroduced": 24},
        {"word": "branding", "definition": "process of creating brand identity", "difficulty": 5, "category": "BUSINESS", "contexts": ["Brand development", "Corporate branding"], "relatedWords": ["identity", "marketing", "image"], "grammarPattern": "branding + strategy/effort", "weekIntroduced": 19},
        {"word": "positioning", "definition": "creating distinct image in market", "difficulty": 6, "category": "BUSINESS", "contexts": ["Market positioning", "Brand positioning"], "relatedWords": ["marketing", "image", "strategy"], "grammarPattern": "positioning + strategy/in", "weekIntroduced": 21},
        {"word": "targeting", "definition": "selecting specific market segment", "difficulty": 5, "category": "BUSINESS", "contexts": ["Market targeting", "Customer targeting"], "relatedWords": ["marketing", "focus", "segment"], "grammarPattern": "targeting + strategy/of", "weekIntroduced": 18},
        {"word": "segmentation", "definition": "division into distinct groups", "difficulty": 6, "category": "BUSINESS", "contexts": ["Market segmentation", "Customer segmentation"], "relatedWords": ["division", "groups", "classification"], "grammarPattern": "segmentation + of/strategy", "weekIntroduced": 20},
        {"word": "demographics", "definition": "statistical data of population", "difficulty": 6, "category": "BUSINESS", "contexts": ["Customer demographics", "Market demographics"], "relatedWords": ["population", "statistics", "data"], "grammarPattern": "demographics + of/analysis", "weekIntroduced": 21},
        {"word": "psychographics", "definition": "study of personality and lifestyle", "difficulty": 7, "category": "BUSINESS", "contexts": ["Consumer psychographics", "Market psychographics"], "relatedWords": ["personality", "lifestyle", "behavior"], "grammarPattern": "psychographics + of/analysis", "weekIntroduced": 25},
        {"word": "ethnographics", "definition": "study of cultural characteristics", "difficulty": 8, "category": "BUSINESS", "contexts": ["Consumer ethnographics", "Market ethnographics"], "relatedWords": ["culture", "ethnicity", "characteristics"], "grammarPattern": "ethnographics + of/study", "weekIntroduced": 27},
        {"word": "geographics", "definition": "study of geographic characteristics", "difficulty": 6, "category": "BUSINESS", "contexts": ["Market geographics", "Customer geographics"], "relatedWords": ["location", "geography", "region"], "grammarPattern": "geographics + of/analysis", "weekIntroduced": 22},
        {"word": "logistics", "definition": "detailed coordination of complex operation", "difficulty": 6, "category": "BUSINESS", "contexts": ["Supply logistics", "Distribution logistics"], "relatedWords": ["coordination", "supply", "distribution"], "grammarPattern": "logistics + of/management", "weekIntroduced": 23},
        {"word": "procurement", "definition": "action of obtaining something", "difficulty": 6, "category": "BUSINESS", "contexts": ["Materials procurement", "Strategic procurement"], "relatedWords": ["purchasing", "acquisition", "sourcing"], "grammarPattern": "procurement + of/process", "weekIntroduced": 24},
        {"word": "sourcing", "definition": "finding suppliers for business", "difficulty": 5, "category": "BUSINESS", "contexts": ["Strategic sourcing", "Global sourcing"], "relatedWords": ["suppliers", "procurement", "purchasing"], "grammarPattern": "sourcing + strategy/from", "weekIntroduced": 20},
        {"word": "wholesaling", "definition": "selling goods in large quantities", "difficulty": 5, "category": "BUSINESS", "contexts": ["Wholesale business", "Wholesaling operation"], "relatedWords": ["bulk", "distribution", "retailers"], "grammarPattern": "wholesaling + business/to", "weekIntroduced": 18},
        {"word": "retailing", "definition": "sale of goods to public", "difficulty": 5, "category": "BUSINESS", "contexts": ["Retail business", "Online retailing"], "relatedWords": ["sales", "customers", "stores"], "grammarPattern": "retailing + business/industry", "weekIntroduced": 17},
        {"word": "e-commerce", "definition": "commercial transactions conducted electronically", "difficulty": 5, "category": "BUSINESS", "contexts": ["E-commerce platform", "Online e-commerce"], "relatedWords": ["online", "digital", "internet"], "grammarPattern": "e-commerce + platform/business", "weekIntroduced": 19},
        {"word": "telecommuting", "definition": "working from home using technology", "difficulty": 6, "category": "BUSINESS", "contexts": ["Telecommuting policy", "Remote telecommuting"], "relatedWords": ["remote", "work", "technology"], "grammarPattern": "telecommuting + policy/option", "weekIntroduced": 22},
        {"word": "freelancing", "definition": "working for different companies", "difficulty": 5, "category": "BUSINESS", "contexts": ["Freelance work", "Freelancing career"], "relatedWords": ["independent", "contract", "self-employed"], "grammarPattern": "freelancing + work/career", "weekIntroduced": 18},
        {"word": "consulting", "definition": "providing expert advice", "difficulty": 5, "category": "BUSINESS", "contexts": ["Management consulting", "Business consulting"], "relatedWords": ["advice", "expertise", "professional"], "grammarPattern": "consulting + services/firm", "weekIntroduced": 19},
        {"word": "auditing", "definition": "official inspection of accounts", "difficulty": 6, "category": "BUSINESS", "contexts": ["Financial auditing", "Internal auditing"], "relatedWords": ["inspection", "verification", "accounts"], "grammarPattern": "auditing + process/firm", "weekIntroduced": 21},
        {"word": "accounting", "definition": "keeping financial accounts", "difficulty": 5, "category": "BUSINESS", "contexts": ["Financial accounting", "Cost accounting"], "relatedWords": ["finances", "records", "bookkeeping"], "grammarPattern": "accounting + system/department", "weekIntroduced": 17},
        {"word": "bookkeeping", "definition": "keeping records of financial affairs", "difficulty": 5, "category": "BUSINESS", "contexts": ["Business bookkeeping", "Financial bookkeeping"], "relatedWords": ["records", "accounts", "finances"], "grammarPattern": "bookkeeping + system/services", "weekIntroduced": 18},
        {"word": "budgeting", "definition": "planning allocation of resources", "difficulty": 5, "category": "BUSINESS", "contexts": ["Financial budgeting", "Project budgeting"], "relatedWords": ["planning", "allocation", "resources"], "grammarPattern": "budgeting + process/for", "weekIntroduced": 17},
        {"word": "forecasting", "definition": "predicting future based on data", "difficulty": 6, "category": "BUSINESS", "contexts": ["Sales forecasting", "Financial forecasting"], "relatedWords": ["prediction", "planning", "analysis"], "grammarPattern": "forecasting + model/for", "weekIntroduced": 20},
        {"word": "planning", "definition": "process of making plans", "difficulty": 4, "category": "BUSINESS", "contexts": ["Strategic planning", "Business planning"], "relatedWords": ["strategy", "preparation", "organization"], "grammarPattern": "planning + process/for", "weekIntroduced": 15},
        {"word": "organizing", "definition": "arranging systematically", "difficulty": 4, "category": "BUSINESS", "contexts": ["Team organizing", "Business organizing"], "relatedWords": ["arrangement", "structure", "coordination"], "grammarPattern": "organizing + process/for", "weekIntroduced": 15},
        {"word": "controlling", "definition": "having power over", "difficulty": 5, "category": "BUSINESS", "contexts": ["Quality controlling", "Cost controlling"], "relatedWords": ["management", "oversight", "regulation"], "grammarPattern": "controlling + process/for", "weekIntroduced": 17},
        {"word": "directing", "definition": "guiding work of others", "difficulty": 5, "category": "BUSINESS", "contexts": ["Team directing", "Project directing"], "relatedWords": ["leadership", "guidance", "supervision"], "grammarPattern": "directing + team/project", "weekIntroduced": 18},
        {"word": "coordinating", "definition": "organizing different elements", "difficulty": 5, "category": "BUSINESS", "contexts": ["Project coordinating", "Team coordinating"], "relatedWords": ["organization", "management", "synchronization"], "grammarPattern": "coordinating + with/between", "weekIntroduced": 19},
        {"word": "supervising", "definition": "observing and directing", "difficulty": 5, "category": "BUSINESS", "contexts": ["Staff supervising", "Project supervising"], "relatedWords": ["oversight", "management", "guidance"], "grammarPattern": "supervising + staff/work", "weekIntroduced": 18},
        {"word": "mentoring", "definition": "teaching or helping someone", "difficulty": 5, "category": "BUSINESS", "contexts": ["Employee mentoring", "Career mentoring"], "relatedWords": ["guidance", "teaching", "support"], "grammarPattern": "mentoring + program/relationship", "weekIntroduced": 19},
        {"word": "coaching", "definition": "training and instruction", "difficulty": 5, "category": "BUSINESS", "contexts": ["Executive coaching", "Performance coaching"], "relatedWords": ["training", "development", "guidance"], "grammarPattern": "coaching + program/session", "weekIntroduced": 18},
        {"word": "training", "definition": "teaching particular skill", "difficulty": 4, "category": "BUSINESS", "contexts": ["Employee training", "Skills training"], "relatedWords": ["education", "development", "learning"], "grammarPattern": "training + program/session", "weekIntroduced": 15},
        {"word": "recruiting", "definition": "finding suitable people for jobs", "difficulty": 5, "category": "BUSINESS", "contexts": ["Talent recruiting", "Employee recruiting"], "relatedWords": ["hiring", "selection", "employment"], "grammarPattern": "recruiting + process/for", "weekIntroduced": 17},
        {"word": "hiring", "definition": "employing someone for job", "difficulty": 4, "category": "BUSINESS", "contexts": ["Staff hiring", "New hiring"], "relatedWords": ["employment", "recruitment", "selection"], "grammarPattern": "hiring + process/decision", "weekIntroduced": 15},
        {"word": "firing", "definition": "dismissing employee from job", "difficulty": 5, "category": "BUSINESS", "contexts": ["Employee firing", "Mass firing"], "relatedWords": ["dismissal", "termination", "layoff"], "grammarPattern": "firing + decision/process", "weekIntroduced": 17},
        {"word": "promoting", "definition": "advancing to higher position", "difficulty": 5, "category": "BUSINESS", "contexts": ["Employee promoting", "Career promoting"], "relatedWords": ["advancement", "elevation", "progress"], "grammarPattern": "promoting + to/for", "weekIntroduced": 18},
        {"word": "demoting", "definition": "reducing to lower position", "difficulty": 6, "category": "BUSINESS", "contexts": ["Employee demoting", "Position demoting"], "relatedWords": ["reduction", "downgrade", "降级"], "grammarPattern": "demoting + to/from", "weekIntroduced": 21},
        {"word": "transferring", "definition": "moving to different position", "difficulty": 5, "category": "BUSINESS", "contexts": ["Employee transferring", "Department transferring"], "relatedWords": ["movement", "relocation", "assignment"], "grammarPattern": "transferring + to/from", "weekIntroduced": 19}
    ]

def add_final_exam_vocabulary():
    return [
        # Additional exam-specific vocabulary (50 words)
        {"word": "methodology", "definition": "system of methods used in activity", "difficulty": 7, "category": "EXAM_SPECIFIC", "contexts": ["Research methodology", "Teaching methodology"], "relatedWords": ["method", "approach", "system"], "grammarPattern": "methodology + of/for", "weekIntroduced": 24},
        {"word": "bibliography", "definition": "list of books on subject", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Research bibliography", "Academic bibliography"], "relatedWords": ["references", "sources", "literature"], "grammarPattern": "bibliography + of/for", "weekIntroduced": 22},
        {"word": "annotation", "definition": "note of explanation or comment", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Text annotation", "Bibliography annotation"], "relatedWords": ["note", "comment", "explanation"], "grammarPattern": "annotation + of/for", "weekIntroduced": 21},
        {"word": "citation", "definition": "quotation from or reference to book", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Academic citation", "Proper citation"], "relatedWords": ["reference", "quotation", "source"], "grammarPattern": "citation + of/for", "weekIntroduced": 20},
        {"word": "reference", "definition": "mention of source of information", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Academic reference", "Bibliography reference"], "relatedWords": ["source", "citation", "mention"], "grammarPattern": "reference + to/for", "weekIntroduced": 17},
        {"word": "plagiarism", "definition": "practice of taking someone's work", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Avoid plagiarism", "Academic plagiarism"], "relatedWords": ["copying", "theft", "academic"], "grammarPattern": "plagiarism + of/in", "weekIntroduced": 21},
        {"word": "paraphrasing", "definition": "expressing meaning using different words", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Text paraphrasing", "Academic paraphrasing"], "relatedWords": ["rewording", "rephrasing", "summary"], "grammarPattern": "paraphrasing + of/technique", "weekIntroduced": 20},
        {"word": "summarizing", "definition": "giving brief statement of main points", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Text summarizing", "Article summarizing"], "relatedWords": ["summary", "condensing", "overview"], "grammarPattern": "summarizing + technique/of", "weekIntroduced": 18},
        {"word": "outlining", "definition": "describing main features", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Essay outlining", "Report outlining"], "relatedWords": ["planning", "structure", "framework"], "grammarPattern": "outlining + process/for", "weekIntroduced": 17},
        {"word": "brainstorming", "definition": "spontaneous group discussion", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Idea brainstorming", "Creative brainstorming"], "relatedWords": ["creativity", "ideas", "discussion"], "grammarPattern": "brainstorming + session/for", "weekIntroduced": 16},
        {"word": "proofreading", "definition": "reading to detect and correct errors", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Essay proofreading", "Document proofreading"], "relatedWords": ["editing", "correction", "review"], "grammarPattern": "proofreading + process/for", "weekIntroduced": 18},
        {"word": "editing", "definition": "preparing written material for publication", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Text editing", "Document editing"], "relatedWords": ["revision", "correction", "improvement"], "grammarPattern": "editing + process/for", "weekIntroduced": 17},
        {"word": "revising", "definition": "examining and improving written work", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Essay revising", "Draft revising"], "relatedWords": ["improvement", "modification", "editing"], "grammarPattern": "revising + process/for", "weekIntroduced": 17},
        {"word": "drafting", "definition": "preparing preliminary version", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Essay drafting", "Report drafting"], "relatedWords": ["writing", "preparation", "preliminary"], "grammarPattern": "drafting + process/stage", "weekIntroduced": 16},
        {"word": "planning", "definition": "deciding in detail how to do something", "difficulty": 4, "category": "EXAM_SPECIFIC", "contexts": ["Essay planning", "Study planning"], "relatedWords": ["preparation", "organization", "strategy"], "grammarPattern": "planning + stage/for", "weekIntroduced": 15},
        {"word": "scanning", "definition": "looking quickly through text", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Text scanning", "Reading scanning"], "relatedWords": ["skimming", "browsing", "searching"], "grammarPattern": "scanning + technique/for", "weekIntroduced": 16},
        {"word": "skimming", "definition": "reading quickly to get general idea", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Text skimming", "Article skimming"], "relatedWords": ["scanning", "browsing", "overview"], "grammarPattern": "skimming + technique/through", "weekIntroduced": 16},
        {"word": "intensive", "definition": "concentrated over short period", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Intensive reading", "Intensive study"], "relatedWords": ["concentrated", "focused", "thorough"], "grammarPattern": "intensive + reading/study", "weekIntroduced": 17},
        {"word": "extensive", "definition": "covering large area", "difficulty": 5, "category": "EXAM_SPECIFIC", "contexts": ["Extensive reading", "Extensive research"], "relatedWords": ["broad", "wide", "comprehensive"], "grammarPattern": "extensive + reading/research", "weekIntroduced": 18},
        {"word": "comprehension", "definition": "ability to understand", "difficulty": 6, "category": "EXAM_SPECIFIC", "contexts": ["Reading comprehension", "Listening comprehension"], "relatedWords": ["understanding", "grasp", "perception"], "grammarPattern": "comprehension + skills/test", "weekIntroduced": 19}
    ]

def add_final_everyday_vocabulary():
    return [
        # Final sophisticated everyday terms (47 words)
        {"word": "sophistication", "definition": "quality of being sophisticated", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Cultural sophistication", "Intellectual sophistication"], "relatedWords": ["refinement", "complexity", "elegance"], "grammarPattern": "sophistication + of/in", "weekIntroduced": 22},
        {"word": "refinement", "definition": "quality of being refined", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Cultural refinement", "Personal refinement"], "relatedWords": ["sophistication", "elegance", "cultivation"], "grammarPattern": "refinement + of/in", "weekIntroduced": 21},
        {"word": "cultivation", "definition": "development of skill or quality", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Mind cultivation", "Skill cultivation"], "relatedWords": ["development", "refinement", "improvement"], "grammarPattern": "cultivation + of/in", "weekIntroduced": 20},
        {"word": "enlightenment", "definition": "state of having knowledge or understanding", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Spiritual enlightenment", "Intellectual enlightenment"], "relatedWords": ["knowledge", "understanding", "wisdom"], "grammarPattern": "enlightenment + about/in", "weekIntroduced": 23},
        {"word": "contemplation", "definition": "thoughtful observation or consideration", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Deep contemplation", "Peaceful contemplation"], "relatedWords": ["meditation", "reflection", "thought"], "grammarPattern": "contemplation + of/in", "weekIntroduced": 22},
        {"word": "meditation", "definition": "practice of focused thinking", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Daily meditation", "Mindfulness meditation"], "relatedWords": ["contemplation", "reflection", "mindfulness"], "grammarPattern": "meditation + practice/on", "weekIntroduced": 19},
        {"word": "introspection", "definition": "examination of own thoughts", "difficulty": 7, "category": "EVERYDAY", "contexts": ["Self introspection", "Deep introspection"], "relatedWords": ["self-examination", "reflection", "analysis"], "grammarPattern": "introspection + into/about", "weekIntroduced": 25},
        {"word": "retrospection", "definition": "consideration of past events", "difficulty": 7, "category": "EVERYDAY", "contexts": ["Personal retrospection", "Life retrospection"], "relatedWords": ["reflection", "looking back", "memory"], "grammarPattern": "retrospection + on/about", "weekIntroduced": 26},
        {"word": "anticipation", "definition": "emotion of looking forward", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Great anticipation", "Eager anticipation"], "relatedWords": ["expectation", "excitement", "hope"], "grammarPattern": "anticipation + of/for", "weekIntroduced": 21},
        {"word": "expectation", "definition": "belief that something will happen", "difficulty": 5, "category": "EVERYDAY", "contexts": ["High expectation", "Reasonable expectation"], "relatedWords": ["anticipation", "hope", "assumption"], "grammarPattern": "expectation + of/for", "weekIntroduced": 18},
        {"word": "assumption", "definition": "thing taken for granted", "difficulty": 5, "category": "EVERYDAY", "contexts": ["False assumption", "Basic assumption"], "relatedWords": ["presumption", "supposition", "belief"], "grammarPattern": "assumption + about/that", "weekIntroduced": 17},
        {"word": "presumption", "definition": "belief based on reasonable evidence", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Legal presumption", "Basic presumption"], "relatedWords": ["assumption", "supposition", "belief"], "grammarPattern": "presumption + of/that", "weekIntroduced": 22},
        {"word": "supposition", "definition": "uncertain belief", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Basic supposition", "Working supposition"], "relatedWords": ["assumption", "hypothesis", "guess"], "grammarPattern": "supposition + that/about", "weekIntroduced": 23},
        {"word": "speculation", "definition": "forming of theory without firm evidence", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Wild speculation", "Financial speculation"], "relatedWords": ["conjecture", "theory", "guess"], "grammarPattern": "speculation + about/on", "weekIntroduced": 21},
        {"word": "conjecture", "definition": "opinion based on incomplete information", "difficulty": 7, "category": "EVERYDAY", "contexts": ["Mathematical conjecture", "Wild conjecture"], "relatedWords": ["speculation", "guess", "theory"], "grammarPattern": "conjecture + about/that", "weekIntroduced": 25},
        {"word": "hypothesis", "definition": "proposed explanation", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Scientific hypothesis", "Working hypothesis"], "relatedWords": ["theory", "supposition", "assumption"], "grammarPattern": "hypothesis + about/that", "weekIntroduced": 20},
        {"word": "proposition", "definition": "statement expressing judgment", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Business proposition", "Logical proposition"], "relatedWords": ["proposal", "suggestion", "offer"], "grammarPattern": "proposition + for/that", "weekIntroduced": 22},
        {"word": "suggestion", "definition": "idea put forward for consideration", "difficulty": 4, "category": "EVERYDAY", "contexts": ["Helpful suggestion", "Make suggestion"], "relatedWords": ["recommendation", "proposal", "advice"], "grammarPattern": "suggestion + for/about", "weekIntroduced": 15},
        {"word": "recommendation", "definition": "suggestion about best course of action", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Strong recommendation", "Personal recommendation"], "relatedWords": ["suggestion", "advice", "endorsement"], "grammarPattern": "recommendation + for/about", "weekIntroduced": 17},
        {"word": "endorsement", "definition": "public support for someone or something", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Celebrity endorsement", "Political endorsement"], "relatedWords": ["support", "approval", "backing"], "grammarPattern": "endorsement + of/for", "weekIntroduced": 21},
        {"word": "approval", "definition": "belief that someone is good", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Seek approval", "Parental approval"], "relatedWords": ["acceptance", "consent", "endorsement"], "grammarPattern": "approval + of/for", "weekIntroduced": 16},
        {"word": "disapproval", "definition": "feeling that something is bad", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Show disapproval", "Express disapproval"], "relatedWords": ["criticism", "rejection", "condemnation"], "grammarPattern": "disapproval + of/for", "weekIntroduced": 18},
        {"word": "appreciation", "definition": "recognition of worth of something", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Show appreciation", "Deep appreciation"], "relatedWords": ["gratitude", "recognition", "understanding"], "grammarPattern": "appreciation + for/of", "weekIntroduced": 17},
        {"word": "depreciation", "definition": "decrease in value", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Currency depreciation", "Asset depreciation"], "relatedWords": ["decline", "reduction", "devaluation"], "grammarPattern": "depreciation + of/in", "weekIntroduced": 22},
        {"word": "deterioration", "definition": "process of becoming worse", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Health deterioration", "Condition deterioration"], "relatedWords": ["decline", "worsening", "degradation"], "grammarPattern": "deterioration + of/in", "weekIntroduced": 23},
        {"word": "improvement", "definition": "instance of becoming better", "difficulty": 4, "category": "EVERYDAY", "contexts": ["Significant improvement", "Show improvement"], "relatedWords": ["enhancement", "betterment", "progress"], "grammarPattern": "improvement + in/of", "weekIntroduced": 15},
        {"word": "enhancement", "definition": "increase or improvement in quality", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Performance enhancement", "Image enhancement"], "relatedWords": ["improvement", "upgrade", "boost"], "grammarPattern": "enhancement + of/in", "weekIntroduced": 20},
        {"word": "optimization", "definition": "action of making best use", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Performance optimization", "Process optimization"], "relatedWords": ["improvement", "maximization", "efficiency"], "grammarPattern": "optimization + of/for", "weekIntroduced": 21},
        {"word": "maximization", "definition": "making as large as possible", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Profit maximization", "Efficiency maximization"], "relatedWords": ["optimization", "increase", "enhancement"], "grammarPattern": "maximization + of/for", "weekIntroduced": 22},
        {"word": "minimization", "definition": "reducing to smallest possible amount", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Risk minimization", "Cost minimization"], "relatedWords": ["reduction", "decrease", "limitation"], "grammarPattern": "minimization + of/for", "weekIntroduced": 23},
        {"word": "stabilization", "definition": "process of making stable", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Economic stabilization", "Emotional stabilization"], "relatedWords": ["balance", "steadying", "normalization"], "grammarPattern": "stabilization + of/in", "weekIntroduced": 24},
        {"word": "normalization", "definition": "process of bringing to normal state", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Relationship normalization", "Situation normalization"], "relatedWords": ["standardization", "regularization", "stabilization"], "grammarPattern": "normalization + of/in", "weekIntroduced": 25},
        {"word": "regularization", "definition": "making regular or normal", "difficulty": 7, "category": "EVERYDAY", "contexts": ["Process regularization", "Status regularization"], "relatedWords": ["normalization", "standardization", "systematization"], "grammarPattern": "regularization + of/in", "weekIntroduced": 26},
        {"word": "systematization", "definition": "arranging according to system", "difficulty": 7, "category": "EVERYDAY", "contexts": ["Knowledge systematization", "Process systematization"], "relatedWords": ["organization", "structuring", "arrangement"], "grammarPattern": "systematization + of/in", "weekIntroduced": 27},
        {"word": "organization", "definition": "action of organizing something", "difficulty": 4, "category": "EVERYDAY", "contexts": ["Event organization", "Time organization"], "relatedWords": ["arrangement", "structure", "coordination"], "grammarPattern": "organization + of/for", "weekIntroduced": 15},
        {"word": "reorganization", "definition": "action of organizing differently", "difficulty": 6, "category": "EVERYDAY", "contexts": ["Company reorganization", "Life reorganization"], "relatedWords": ["restructuring", "rearrangement", "reform"], "grammarPattern": "reorganization + of/in", "weekIntroduced": 21},
        {"word": "coordination", "definition": "organization of different elements", "difficulty": 5, "category": "EVERYDAY", "contexts": ["Team coordination", "Movement coordination"], "relatedWords": ["cooperation", "collaboration", "synchronization"], "grammarPattern": "coordination + of/between", "weekIntroduced": 18}
    ]

def main():
    vocab_data = load_vocabulary()
    current_count = len(vocab_data)
    print(f"Current vocabulary: {current_count} words")

    # Add all final vocabulary sets
    new_words = []
    new_words.extend(add_final_academic_vocabulary())
    new_words.extend(add_final_business_vocabulary())
    new_words.extend(add_final_exam_vocabulary())
    new_words.extend(add_final_everyday_vocabulary())

    # Filter out duplicates
    existing_words = {item["word"].lower() for item in vocab_data}
    unique_new_words = [word for word in new_words if word["word"].lower() not in existing_words]

    vocab_data.extend(unique_new_words)

    # Save the updated database
    save_vocabulary(vocab_data)

    # Print statistics
    final_count = len(vocab_data)
    added_count = len(unique_new_words)
    print(f"Added {added_count} new words")
    print(f"Total vocabulary: {final_count} words")

    # Category distribution
    from collections import Counter
    categories = Counter(item["category"] for item in vocab_data)
    print(f"Final category distribution: {dict(categories)}")

    if final_count >= 2000:
        print("🎉 TARGET ACHIEVED: 2000+ words!")
        print(f"🎯 SUCCESS: Database now contains {final_count} words for YDS/YÖKDİL exam preparation!")
        print("📚 The vocabulary database is now ready for Phase 1 implementation.")
    else:
        remaining = 2000 - final_count
        print(f"Still need {remaining} more words to reach 2000")

if __name__ == "__main__":
    main()