// app/src/main/java/com/mtlc/studyplan/ui/theme/Color.kt

package com.mtlc.studyplan.ui.theme

import androidx.compose.ui.graphics.Color

private fun hexColor(value: Long): Color = Color(value)

// Light Colors
val md_theme_light_primary = hexColor(0xFF006764)
val md_theme_light_onPrimary = hexColor(0xFFFFFFFF)
val md_theme_light_primaryContainer = hexColor(0xFF70F7F3)
val md_theme_light_onPrimaryContainer = hexColor(0xFF00201F)
val md_theme_light_secondary = hexColor(0xFF4A6361)
val md_theme_light_onSecondary = hexColor(0xFFFFFFFF)
val md_theme_light_secondaryContainer = hexColor(0xFFCCE8E5)
val md_theme_light_onSecondaryContainer = hexColor(0xFF051F1E)
val md_theme_light_tertiary = hexColor(0xFF4D60C9)
val md_theme_light_onTertiary = hexColor(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = hexColor(0xFFDEE0FF)
val md_theme_light_onTertiaryContainer = hexColor(0xFF001944)
val md_theme_light_error = hexColor(0xFFBA1A1A)
val md_theme_light_onError = hexColor(0xFFFFFFFF)
val md_theme_light_errorContainer = hexColor(0xFFFFDAD6)
val md_theme_light_onErrorContainer = hexColor(0xFF410002)
val md_theme_light_outline = hexColor(0xFF6F7978)
val md_theme_light_background = hexColor(0xFFEFF6FF)
val md_theme_light_onBackground = hexColor(0xFF191C1C)
val md_theme_light_surface = hexColor(0xFFF4F8FF)
val md_theme_light_onSurface = hexColor(0xFF191C1C)
val md_theme_light_surfaceVariant = hexColor(0xFFDBE5E3)
val md_theme_light_onSurfaceVariant = hexColor(0xFF3F4948)
val md_theme_light_inverseSurface = hexColor(0xFF2D3130)
val md_theme_light_inverseOnSurface = hexColor(0xFFEEF2F1)
val md_theme_light_inversePrimary = hexColor(0xFF4ADAD6)
val md_theme_light_surfaceTint = hexColor(0xFF006764) // primary color
val md_theme_light_outlineVariant = hexColor(0xFFBEC9C7)
val md_theme_light_scrim = hexColor(0xFF000000)

// Dark Colors
val md_theme_dark_primary = hexColor(0xFFA4C8FF)
val md_theme_dark_onPrimary = hexColor(0xFF003060)
val md_theme_dark_primaryContainer = hexColor(0xFF004788)
val md_theme_dark_onPrimaryContainer = hexColor(0xFFD3E3FD)
val md_theme_dark_secondary = hexColor(0xFFBEC6DC)
val md_theme_dark_onSecondary = hexColor(0xFF283141)
val md_theme_dark_secondaryContainer = hexColor(0xFF3E4758)
val md_theme_dark_onSecondaryContainer = hexColor(0xFFDAE2F9)
val md_theme_dark_tertiary = hexColor(0xFFDEBCDF)
val md_theme_dark_onTertiary = hexColor(0xFF3E2844)
val md_theme_dark_tertiaryContainer = hexColor(0xFF563E5C)
val md_theme_dark_onTertiaryContainer = hexColor(0xFFFAD8FD)
val md_theme_dark_error = hexColor(0xFFFFB4AB)
val md_theme_dark_onError = hexColor(0xFF690005)
val md_theme_dark_errorContainer = hexColor(0xFF93000A)
val md_theme_dark_onErrorContainer = hexColor(0xFFFFDAD6)
val md_theme_dark_outline = hexColor(0xFF91909A)
val md_theme_dark_background = hexColor(0xFF111318)
val md_theme_dark_onBackground = hexColor(0xFFE2E2E6)
val md_theme_dark_surface = hexColor(0xFF111318)
val md_theme_dark_onSurface = hexColor(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = hexColor(0xFF44474F)
val md_theme_dark_onSurfaceVariant = hexColor(0xFFC4C6D0)
val md_theme_dark_inverseSurface = hexColor(0xFFE2E2E6)
val md_theme_dark_inverseOnSurface = hexColor(0xFF2F3033)
val md_theme_dark_inversePrimary = hexColor(0xFF1976D2)
val md_theme_dark_surfaceTint = hexColor(0xFFA4C8FF)
val md_theme_dark_outlineVariant = hexColor(0xFF44474F)
val md_theme_dark_scrim = hexColor(0xFF000000)
