// app/src/main/java/com/mtlc/studyplan/ui/theme/Color.kt

package com.mtlc.studyplan.ui.theme

import androidx.compose.ui.graphics.Color

private fun hexColor(value: Long): Color = Color(value)

// Light Colors (Açik Tema Renkleri)
val md_theme_light_primary = hexColor(0xFF006764)
val md_theme_light_onPrimary = hexColor(0xFFFFFFFF)
val md_theme_light_primaryContainer = hexColor(0xFF70F7F3)
val md_theme_light_onPrimaryContainer = hexColor(0xFF00201F)
val md_theme_light_secondary = hexColor(0xFF4A6361)
val md_theme_light_onSecondary = hexColor(0xFFFFFFFF)
val md_theme_light_secondaryContainer = hexColor(0xFFCCE8E5)
val md_theme_light_onSecondaryContainer = hexColor(0xFF051F1E)
val md_theme_light_tertiary = hexColor(0xFF4D60C9)
val md_theme_light_onTertiary = hexColor(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = hexColor(0xFFDEE0FF)
val md_theme_light_onTertiaryContainer = hexColor(0xFF001944)
val md_theme_light_error = hexColor(0xFFBA1A1A)
val md_theme_light_onError = hexColor(0xFFFFFFFF)
val md_theme_light_errorContainer = hexColor(0xFFFFDAD6)
val md_theme_light_onErrorContainer = hexColor(0xFF410002)
val md_theme_light_outline = hexColor(0xFF6F7978)
val md_theme_light_background = hexColor(0xFFFBFDFA)
val md_theme_light_onBackground = hexColor(0xFF191C1C)
val md_theme_light_surface = hexColor(0xFFFBFDFA)
val md_theme_light_onSurface = hexColor(0xFF191C1C)
val md_theme_light_surfaceVariant = hexColor(0xFFDBE5E3)
val md_theme_light_onSurfaceVariant = hexColor(0xFF3F4948)
val md_theme_light_inverseSurface = hexColor(0xFF2D3130)
val md_theme_light_inverseOnSurface = hexColor(0xFFEEF2F1)
val md_theme_light_inversePrimary = hexColor(0xFF4ADAD6)
val md_theme_light_surfaceTint = hexColor(0xFF006764) // primary color
val md_theme_light_outlineVariant = hexColor(0xFFBEC9C7)
val md_theme_light_scrim = hexColor(0xFF000000)

// Dark Colors (Koyu Tema Renkleri)
val md_theme_dark_primary = hexColor(0xFF4ADAD6)
val md_theme_dark_onPrimary = hexColor(0xFF003735)
val md_theme_dark_primaryContainer = hexColor(0xFF00504C)
val md_theme_dark_onPrimaryContainer = hexColor(0xFF70F7F3)
val md_theme_dark_secondary = hexColor(0xFFB0CCC9)
val md_theme_dark_onSecondary = hexColor(0xFF1C3533)
val md_theme_dark_secondaryContainer = hexColor(0xFF334B49)
val md_theme_dark_onSecondaryContainer = hexColor(0xFFCCE8E5)
val md_theme_dark_tertiary = hexColor(0xFFB9C3FF)
val md_theme_dark_onTertiary = hexColor(0xFF1D2F5F)
val md_theme_dark_tertiaryContainer = hexColor(0xFF354792)
val md_theme_dark_onTertiaryContainer = hexColor(0xFFDEE0FF)
val md_theme_dark_error = hexColor(0xFFFFB4AB)
val md_theme_dark_onError = hexColor(0xFF690005)
val md_theme_dark_errorContainer = hexColor(0xFF93000A)
val md_theme_dark_onErrorContainer = hexColor(0xFFFFDAD6)
val md_theme_dark_outline = hexColor(0xFF889391)
val md_theme_dark_background = hexColor(0xFF191C1C)
val md_theme_dark_onBackground = hexColor(0xFFE0E3E2)
val md_theme_dark_surface = hexColor(0xFF191C1C)
val md_theme_dark_onSurface = hexColor(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = hexColor(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = hexColor(0xFFBEC9C7)
val md_theme_dark_inverseSurface = hexColor(0xFFE0E3E2)
val md_theme_dark_inverseOnSurface = hexColor(0xFF191C1C)
val md_theme_dark_inversePrimary = hexColor(0xFF006764)
val md_theme_dark_surfaceTint = hexColor(0xFF4ADAD6) // primary color
val md_theme_dark_outlineVariant = hexColor(0xFF3F4948)
val md_theme_dark_scrim = hexColor(0xFF000000)
